#################################################################################################
# Makefile for CHAPSim2, by Wei Wang, July 2021                                                 #
# Updated: Dec 2024 - Incremental compilation enabled                                           #
# Usage:                                                                                        #
#       make all        to make all files with -O2                                              #
#       make cfg=gnu    to debug for gfortran compiler                                          #
#       make cfg=intel  to debug for intel compiler                                             #
#       make cfg=cray   to make for cray                                                        #
# For debugging run:                                                                            #
# mpirun -np 4 valgrind --leak-check=full --track-origins=yes \                                 #
#                       --log-file=valgrind_output.txt ./CHAPSIM*                               #
#                          < solver_input > solver_output                                       #
#################################################################################################
.SUFFIXES:
.PHONY: debug default clean all

PROGRAM= CHAPSim

ifeq ($(cfg), gnu)
  FOPTS= -O -g -Wall -fbacktrace -fbounds-check -fcheck=all -ffpe-trap=invalid,zero,overflow \
  -ffree-line-length-512 -Wuninitialized -Wmaybe-uninitialized \
   -Wno-unused -cpp
  FOPTS += -fallow-argument-mismatch
  FFLGS= -DDOUBLE_PREC -fdefault-real-8 -fdefault-double-8
  FDEBG= -DDEBUG_STEPS #-DDEBUG_STEPS #-DDEBUG_ALGO# -DDEBUG_FFT # -DDEBUG_TEST -DDEBUG_FFT
else ifeq ($(cfg), intel)
  FOPTS= -g -assume ieee_fpe_flags -check all -check bounds -check uninit -debug all \
	-fp-stack-check fpe0 -fpe3 -fpe-all=3 -ftrapuv -ftz -warn all, nounused, -fpp
  FFLGS= -DDOUBLE_PREC -DDEBUG
  FDEBG= -DDEBUG_STEPS -DDEBUG_FFT
else ifeq ($(cfg), cray)
  FOPTS= -cpp # -m 3
  FFLGS= # -s default64
  FDEBG= -DDEBUG_STEPS -DDEBUG_FFT
else ifeq ($(cfg), pg)
  FOPTS= -O3 -pg -march=native  -Wall -fimplicit-none  -ffree-line-length-512  -fwhole-file  -std=gnu \
	-ffpe-trap=invalid,zero,overflow -fall-intrinsics, -cpp
  FFLGS= -DDOUBLE_PREC 
  FDEBG= -DDEBUG_STEPS -DDEBUG_FFT
else
  FOPTS= -O3 -Wall -fbacktrace -fbounds-check -fcheck=all -ffpe-trap=invalid,zero,overflow \
   -finit-local-zero -ffree-line-length-512 -Wno-unused, -cpp
  # For gcc-10 and higher (comment out for older versions)
  FOPTS += -fallow-argument-mismatch	
  FFLGS= -DDOUBLE_PREC
  FDEBG= #-DDEBUG_STEPS # -DDEBUG_FFT -DDEBUG_VISU
endif

include ./lib/2decomp_fft_updated/src/Makefile.inc
INCLUDE= -I./lib/2decomp_fft_updated/include
LIBS= -L./lib/2decomp_fft_updated/lib -l2decomp_fft

DIR_SRC= ./src
DIR_BIN= ./bin
DIR_OBJ= ./obj

OBJS1= modules.o\
      tools_general.o\
      input_thermo.o\
      bc_dirichlet.o\
      bc_convective_outlet.o\
      bc_ndomain_interior.o\
      bc_general.o\
      input_general.o\
      basics_algorithms.o\
      basics_operations2.o\
      tools_solver.o\
      para_conversion.o\
      geometry.o\
      io_tools.o\
      io_monitor.o\
      io_visulisation.o\
      post_statistics.o\
      domain_decomposition.o\
      poisson_interface.o\
      poisson_1stderivcomp.o\
      eq_continuity.o\
      eq_energy.o\
      io_restart.o\
      eq_momentum2.o\
      initialisation.o\
      test_algrithms.o\
      chapsim.o
OBJS = $(OBJS1:%=$(DIR_OBJ)/%)

default: all

$(DIR_BIN)/$(PROGRAM): $(OBJS)
	@echo "\n ====== Linking... ====== \n"
	$(FC) $(FOPTS) $(FFLGS) $(FDEBG) -o $@ $^ $(LIBS)

$(DIR_OBJ)/%.o : $(DIR_SRC)/%.f90
	@mkdir -p $(DIR_OBJ)
	$(FC) $(INCLUDE) $(FOPTS) $(FFLGS) $(FDEBG) -c -o $@ $<

all: $(DIR_BIN)/$(PROGRAM)
	@echo "\n ====== Successfully compiled ====== \n"

clean:
	@echo "\n ====== Cleaning build files... ====== \n"
	@rm -f $(DIR_OBJ)/*.o $(DIR_OBJ)/*.mod $(DIR_BIN)/$(PROGRAM)
