chapsim.f90
program chapsim
References finalise_chapsim, initialize_chapsim, solve_eqs_iteration.
subroutine initialize_chapsim
Initialisation and preprocessing of geometry, mesh and tools This subroutine is called at beginning of the main program.
References poisson_interface_mod::build_up_poisson_interface, geometry_mod::buildup_geometry_mesh_info, domain_decomposition_mod::buildup_mpi_domain_decomposition, thermo_info_mod::buildup_thermo_mapping_relations, code_performance_mod::call_cpu_time, code_performance_mod::cpu_time_code_start, files_io_mod::create_directory, decomp_2d_poisson::decomp_2d_poisson_init, flow_thermo_initialiasation::initialize_flow_fields, mpi_mod::initialize_mpi, flow_thermo_initialiasation::initialize_thermo_fields, mpi_mod::nxdomain, operations::prepare_lhs_coeffs_for_operations, print_debug_end_msg, print_debug_start_msg, input_general_mod::read_input_parameters, test_algorithms.
Referenced by chapsim.
subroutine solve_eqs_iteration
solve the governing equations in iteration
This subroutine is the main solver. none NA none NA
References code_performance_mod::call_cpu_time, solver_tools_mod::check_cfl_convection, solver_tools_mod::check_cfl_diffusion, continuity_eq_mod::check_mass_conservation, input_general_mod::cpu_nfre, code_performance_mod::cpu_time_iter_end, code_performance_mod::cpu_time_iter_start, code_performance_mod::cpu_time_step_end, code_performance_mod::cpu_time_step_start, vars_df_mod::domain, solver_tools_mod::find_maximum_absvar3d, vars_df_mod::flow, mpi_mod::nxdomain, print_debug_start_msg, eq_energy_mod::solve_energy_eq, eq_momentum_mod::solve_momentum_eq, vars_df_mod::thermo, solver_tools_mod::update_prgr, solver_tools_mod::update_re, statistics_mod::update_statistics_flow, statistics_mod::update_statistics_thermo, io_restart_mod::write_instantanous_flow_raw_data, io_restart_mod::write_instantanous_thermo_raw_data, io_monitor_mod::write_monitor_flow, io_monitor_mod::write_monitor_thermo, io_monitor_mod::write_monitor_total, io_visulisation_mod::write_snapshot_flow, io_visulisation_mod::write_snapshot_flow_stat, io_visulisation_mod::write_snapshot_thermo, io_visulisation_mod::write_snapshot_thermo_stat, statistics_mod::write_statistics_flow, statistics_mod::write_statistics_thermo, wtformat_mod::wrtfmt1e.
Referenced by chapsim.
subroutine finalise_chapsim
References code_performance_mod::call_cpu_time, code_performance_mod::cpu_time_code_end, mpi_mod::finalise_mpi.
Referenced by chapsim.