decomp_2d_poisson
real(mytype), parameter decomp_2d_poisson::epsilon
Referenced by poisson_000, poisson_010, poisson_100, poisson_11x.
integer save decomp_2d_poisson::bcx
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, waves.
integer save decomp_2d_poisson::bcy
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, waves.
integer save decomp_2d_poisson::bcz
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, matrice_refinement, poisson_11x, waves.
type(decomp_info), save decomp_2d_poisson::ph
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_010, poisson_100, poisson_11x.
type(decomp_info), save decomp_2d_poisson::sp
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, matrice_refinement, poisson_000, poisson_010, poisson_100, poisson_11x, waves.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::az
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::bz
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::ay
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::by
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::ax
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::bx
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
complex(mytype), dimension(:,:,:), allocatable, save decomp_2d_poisson::kxyz
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine, waves.
complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a
Referenced by complex_half_unit, decomp_2d_poisson_finalize, decomp_2d_poisson_init, matrice_refinement, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a2
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, matrice_refinement, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a3
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, matrice_refinement, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw1
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw1b
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw2
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw2b
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw3
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw1
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw1b
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, fft3d_sp_shift_half_y1, matrice_refinement, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw22
Referenced by decomp_2d_poisson_init, matrice_refinement, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2b
Referenced by decomp_2d_poisson_finalize, decomp_2d_poisson_init, fft3d_sp_shift_half_y1, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2c
Referenced by decomp_2d_poisson_init, poisson_010, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
logical save decomp_2d_poisson::fft_initialised
Referenced by decomp_2d_poisson_finalize, poisson_000, poisson_010, poisson_100, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
procedure (poisson_xxx), pointer, public decomp_2d_poisson::poisson
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx, eq_momentum_mod::solve_poisson, eq_momentum_mod::solve_poisson_x2z.
complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfx
Referenced by complex_half_unit, fft3d_sp_shift_half_x0, fft3d_sp_shift_half_x1.
complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfy
Referenced by complex_half_unit, fft3d_sp_shift_half_y0, fft3d_sp_shift_half_y1.
complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfz
Referenced by complex_half_unit, fft3d_sp_shift_half_z0.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wx
Referenced by complex_half_unit, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wy
Referenced by complex_half_unit, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wz
Referenced by complex_half_unit, decomp_2d_poisson::poisson_xxx::poisson_xxx, subroutine.
subroutine public decomp_2d_poisson::decomp_2d_poisson_init()
References a, a2, a3, abxyz, ax, ay, az, bcx, bcy, bcz, bx, by, bz, cw1, cw1b, cw2, cw22, cw2b, cw2c, poisson_interface_mod::istret, kxyz, matrice_refinement, poisson_interface_mod::nclx, poisson_interface_mod::ncly, poisson_interface_mod::nclz, poisson_interface_mod::nx, poisson_interface_mod::ny, poisson_interface_mod::nym, poisson_interface_mod::nz, ph, poisson, poisson_000, poisson_010, poisson_100, poisson_11x, rw1, rw1b, rw2, rw2b, rw3, sp, waves.
Referenced by initialize_chapsim, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine public decomp_2d_poisson::decomp_2d_poisson_finalize
References a, a2, a3, ax, ay, az, bcx, bcy, bcz, bx, by, bz, cw1, cw1b, cw2, cw2b, fft_initialised, kxyz, ph, rw1, rw1b, rw2, rw2b, rw3, sp.
Referenced by decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::poisson_000(rhs)
References avg3d, ax, ay, az, bx, by, bz, cw1, cx, epsilon, fft_initialised, iy, kxyz, rl, sp.
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::poisson_100(rhs)
References ax, ay, az, bx, by, bz, cw1, cw1b, cx, epsilon, fft_initialised, iy, kxyz, ph, rl, rw1, rw1b, rw2, sp.
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::poisson_010(rhs)
References a, a2, a3, ax, ay, az, bx, by, bz, cw1, cw2, cw2b, cw2c, cx, epsilon, fft_initialised, inversion5_v1, inversion5_v2, poisson_interface_mod::istret, iy, kxyz, ph, rl, rw2, rw2b, sp.
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::poisson_11x(rhs)
References a, a2, a3, avg3d, ax, ay, az, bcz, bx, by, bz, cw1, cw1b, cw2, cw2b, cw2c, cx, epsilon, fft_initialised, inversion5_v1, inversion5_v2, poisson_interface_mod::istret, iy, kxyz, matrice_refinement, ph, rl, rw1, rw1b, rw2, rw2b, rw3, sp.
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::abxyz(ax, ay, az, bx, by, bz, nx, ny, nz, bcx, bcy, bcz)
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::waves()
References poisson_interface_mod::acix6, poisson_interface_mod::aciy6, poisson_interface_mod::aciz6, poisson_interface_mod::alcaix6, poisson_interface_mod::alcaiy6, poisson_interface_mod::alcaiz6, poisson_interface_mod::bcix6, poisson_interface_mod::bciy6, poisson_interface_mod::bciz6, bcx, bcy, bcz, cx, poisson_interface_mod::dx, poisson_interface_mod::dy, poisson_interface_mod::dz, poisson_interface_mod::exs, poisson_interface_mod::eys, poisson_interface_mod::ezs, poisson_interface_mod::istret, kxyz, poisson_interface_mod::nx, poisson_interface_mod::nxm, poisson_interface_mod::ny, poisson_interface_mod::nym, poisson_interface_mod::nz, poisson_interface_mod::nzm, sp, poisson_interface_mod::xk2, poisson_interface_mod::xkx, poisson_interface_mod::xlx, poisson_interface_mod::yk2, poisson_interface_mod::yky, poisson_interface_mod::yly, poisson_interface_mod::zk2, poisson_interface_mod::zkz, poisson_interface_mod::zlz.
Referenced by decomp_2d_poisson_init, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::matrice_refinement()
References a, a2, a3, bcz, cw2, cw22, cx, iy, rl, sp.
Referenced by decomp_2d_poisson_init, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::avg3d(var, avg)
Referenced by poisson_000, poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine, private decomp_2d_poisson::complex_half_unit
References a, cplx_circle_unit_halfx, cplx_circle_unit_halfy, cplx_circle_unit_halfz, poisson_interface_mod::nx, poisson_interface_mod::ny, poisson_interface_mod::nz, wx, wy, wz.
Referenced by decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::fft3d_sp_shift_half_x0(cw1, isign)
References cplx_circle_unit_halfx, poisson_interface_mod::ibackward, poisson_interface_mod::iforward, poisson_interface_mod::nx.
Referenced by decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::fft3d_sp_shift_half_x1(cw1, isign)
References cplx_circle_unit_halfx, poisson_interface_mod::ibackward, poisson_interface_mod::iforward, poisson_interface_mod::nx.
subroutine decomp_2d_poisson::fft3d_sp_shift_half_y0(cw1, isign)
References cplx_circle_unit_halfy, poisson_interface_mod::ibackward, poisson_interface_mod::iforward, poisson_interface_mod::ny.
Referenced by decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::fft3d_sp_shift_half_y1(cw1)
References cplx_circle_unit_halfy, cw2, cw2b, poisson_interface_mod::ibackward, poisson_interface_mod::iforward, poisson_interface_mod::ny.
subroutine decomp_2d_poisson::fft3d_sp_shift_half_z0(cw1, isign)
References cplx_circle_unit_halfz, poisson_interface_mod::ibackward, poisson_interface_mod::iforward.
Referenced by decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine decomp_2d_poisson::subroutine()
References a, a2, a3, poisson_interface_mod::acix6, poisson_interface_mod::aciy6, poisson_interface_mod::aciz6, poisson_interface_mod::alcaix6, poisson_interface_mod::alcaiy6, poisson_interface_mod::alcaiz6, poisson_interface_mod::bcix6, poisson_interface_mod::bciy6, poisson_interface_mod::bciz6, cw2, cw22, cx, poisson_interface_mod::istret, iy, kxyz, poisson_interface_mod::nx, poisson_interface_mod::ny, poisson_interface_mod::nz, rl, wx, wy, wz, poisson_interface_mod::xk2, poisson_interface_mod::xkx, poisson_interface_mod::yk2, poisson_interface_mod::yky, poisson_interface_mod::yly, poisson_interface_mod::zk2, poisson_interface_mod::zkz.