thermo_info_mod
integer, save thermo_info_mod::n_func2table
Referenced by buildup_property_relations_from_function, initialize_thermo_parameters.
logical thermo_info_mod::is_ftplist_dim
Referenced by buildup_property_relations_from_function, buildup_property_relations_from_table, ftp_get_thermal_properties_dimensional_from_t, ftp_refresh_thermal_properties_from_dh, initialize_thermo_parameters.
type(t_fluidthermoproperty), dimension(:), allocatable, save thermo_info_mod::ftplist
Referenced by buildup_property_relations_from_function, buildup_property_relations_from_table, ftp_get_thermal_properties_dimensional_from_t, ftp_is_t_in_scope, ftp_refresh_thermal_properties_from_dh, ftp_refresh_thermal_properties_from_h, ftp_refresh_thermal_properties_from_t_undim, ftplist_check_monotonicity_dh_of_hort, ftplist_sort_t_small2big, write_thermo_property.
type(t_fluid_parameter), save thermo_info_mod::fluidparam
Referenced by buildup_property_relations_from_function, buildup_property_relations_from_table, buildup_thermo_mapping_relations, convert_thermo_bc_from_dim_to_undim, ftp_convert_undim_to_dim, ftp_get_thermal_properties_dimensional_from_t, ftp_is_t_in_scope, ftp_refresh_thermal_properties_from_dh, ftp_refresh_thermal_properties_from_h, ftp_refresh_thermal_properties_from_t_undim, ftplist_check_monotonicity_dh_of_hort, ftplist_sort_t_small2big, initialize_thermal_properties, initialize_thermo_parameters, solver_tools_mod::update_prgr, write_thermo_property.
subroutine, private thermo_info_mod::ftp_is_t_in_scope(this)
Defination of a procedure in the type t_fluidThermoProperty. to check the temperature limitations.
This subroutine is called as required to check the temperature of given element is within the given limits as a single phase flow. this a cell element with udf property
References fluidparam, ftplist, parameters_constant_mod::iproperty_funcs, parameters_constant_mod::iproperty_table, wtformat_mod::wrtfmt3r.
Referenced by write_thermo_property.
subroutine, private thermo_info_mod::ftp_get_thermal_properties_dimensional_from_t(this)
Defination of a procedure in the type t_fluidThermoProperty. to update the thermal properties based on the known temperature.
This subroutine is called as required to update all thermal properties from the known temperature (dimensional or dimensionless). this a cell element with udf property dim an optional indicator of dimensional /dimensionless T. Exsiting of dim indicates the known/given T is dimensional. Otherwise, not.
References parameters_constant_mod::com_bi, parameters_constant_mod::com_lbe, parameters_constant_mod::com_na, parameters_constant_mod::com_pb, fluidparam, ftplist, parameters_constant_mod::iliquid_bismuth, parameters_constant_mod::iliquid_lbe, parameters_constant_mod::iliquid_lead, parameters_constant_mod::iliquid_sodium, parameters_constant_mod::iproperty_funcs, parameters_constant_mod::iproperty_table, is_ftplist_dim, parameters_constant_mod::minp, parameters_constant_mod::one, print_error_msg, parameters_constant_mod::zero.
Referenced by buildup_property_relations_from_function, buildup_property_relations_from_table.
subroutine, private thermo_info_mod::ftp_refresh_thermal_properties_from_t_undim(this)
References parameters_constant_mod::com_bi, parameters_constant_mod::com_lbe, parameters_constant_mod::com_na, parameters_constant_mod::com_pb, fluidparam, ftplist, parameters_constant_mod::iliquid_bismuth, parameters_constant_mod::iliquid_lbe, parameters_constant_mod::iliquid_lead, parameters_constant_mod::iliquid_sodium, parameters_constant_mod::iproperty_funcs, parameters_constant_mod::iproperty_table, parameters_constant_mod::minp, parameters_constant_mod::one, parameters_constant_mod::zero.
Referenced by buildup_property_relations_from_function, convert_thermo_bc_from_dim_to_undim, ftp_refresh_thermal_properties_from_dh, initialize_thermal_properties.
subroutine, private thermo_info_mod::ftp_refresh_thermal_properties_from_h(this)
Defination of a procedure in the type t_fluidThermoProperty. to update the thermal properties based on the known enthalpy.
This subroutine is called as required to update all thermal properties from the known enthalpy (dimensionless only). this a cell element with udf property
References fluidparam, ftplist, parameters_constant_mod::minp, parameters_constant_mod::one.
Referenced by ftp_refresh_thermal_properties_from_dh.
subroutine, public thermo_info_mod::ftp_refresh_thermal_properties_from_dh(this)
Defination of a procedure in the type t_fluidThermoProperty. to update the thermal properties based on the known enthalpy per unit mass.
This subroutine is called as required to update all thermal properties from the known enthalpy per unit mass (dimensionless only). this a cell element with udf property
References fluidparam, ftp_refresh_thermal_properties_from_h, ftp_refresh_thermal_properties_from_t_undim, ftplist, parameters_constant_mod::iproperty_funcs, parameters_constant_mod::iproperty_table, is_ftplist_dim, parameters_constant_mod::minp, parameters_constant_mod::one, print_error_msg, print_warning_msg.
Referenced by update_thermal_properties, write_thermo_property.
subroutine, private thermo_info_mod::ftp_print(this, unit, iotype, v_list, iostat, iomsg)
Defination of a procedure in the type t_fluidThermoProperty. to print out the thermal properties at the given element.
This subroutine is called as required to print out thermal properties for degbugging. this a cell element with udf property unit iotype v_list iostat iomsg
subroutine, private thermo_info_mod::ftplist_sort_t_small2big
Sort out the user given thermal property table based on the temperature from small to big.
This subroutine is called locally once reading in the given thermal table. list the thermal table element array
References fluidparam, ftplist.
Referenced by buildup_property_relations_from_table.
subroutine, private thermo_info_mod::ftplist_check_monotonicity_dh_of_hort
Check the monotonicity of the $\rho h$ along $h$ and $T$.
This subroutine is called locally once building up the thermal property relationships. Non-monotonicity could happen in fluids at supercritical pressure when inproper reference temperature is given. none NA
References fluidparam, ftplist, parameters_constant_mod::minp.
Referenced by buildup_property_relations_from_function, buildup_property_relations_from_table.
subroutine, private thermo_info_mod::buildup_property_relations_from_table
Building up the thermal property relations from the given table. This subroutine is called once after reading the table. [mpi] all ranks.
ref_T0 reference temperature
References fluidparam, ftp_get_thermal_properties_dimensional_from_t, ftplist, ftplist_check_monotonicity_dh_of_hort, ftplist_sort_t_small2big, is_ftplist_dim, print_debug_mid_msg, print_debug_start_msg, wtformat_mod::wrtfmt1e, wtformat_mod::wrtfmt1r, wtformat_mod::wrtfmt2r.
Referenced by buildup_thermo_mapping_relations.
subroutine, private thermo_info_mod::ftp_convert_undim_to_dim(ftp_undim, ftp_dim)
References fluidparam.
Referenced by write_thermo_property.
subroutine, private thermo_info_mod::buildup_property_relations_from_function
Building up the thermal property relations from defined relations.
This subroutine is called once after defining the relations. none NA
References fluidparam, ftp_get_thermal_properties_dimensional_from_t, ftp_refresh_thermal_properties_from_t_undim, ftplist, ftplist_check_monotonicity_dh_of_hort, is_ftplist_dim, n_func2table, print_debug_mid_msg, print_debug_start_msg, wtformat_mod::wrtfmt1e, wtformat_mod::wrtfmt1r, wtformat_mod::wrtfmt2r.
Referenced by buildup_thermo_mapping_relations.
subroutine, private thermo_info_mod::write_thermo_property
Write out the rebuilt thermal property relations.
This subroutine is called for testing. none NA
References fluidparam, ftp_convert_undim_to_dim, ftp_is_t_in_scope, ftp_refresh_thermal_properties_from_dh, ftplist, parameters_constant_mod::truncerr.
Referenced by buildup_thermo_mapping_relations.
subroutine, private thermo_info_mod::initialize_thermo_parameters(tm)
Identify table or equations for thermal properties based on input fluid material.
This subroutine is called once in setting up thermal relations. [mpi] all ranks none NA
References fluidparam, is_ftplist_dim, n_func2table, print_debug_end_msg, print_debug_start_msg.
Referenced by buildup_thermo_mapping_relations.
subroutine, private thermo_info_mod::convert_thermo_bc_from_dim_to_undim(tm, dm)
References fluidparam, ftp_refresh_thermal_properties_from_t_undim, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann.
Referenced by buildup_thermo_mapping_relations.
subroutine, public thermo_info_mod::initialize_thermal_properties(fl, tm)
Initialise thermal variables if ithermo = 1.
Scope: mpi called-freq xdomain module all once specified private fl flow type tm thermo type
References fluidparam, ftp_refresh_thermal_properties_from_t_undim, print_debug_end_msg, print_debug_mid_msg.
Referenced by flow_thermo_initialiasation::initialize_thermo_fields.
subroutine, public thermo_info_mod::buildup_thermo_mapping_relations(tm, dm)
The main code for thermal property initialisation. Scope: mpi called-freq xdomain all once all.
none NA
References buildup_property_relations_from_function, buildup_property_relations_from_table, convert_thermo_bc_from_dim_to_undim, fluidparam, initialize_thermo_parameters, write_thermo_property.
Referenced by initialize_chapsim.
subroutine, public thermo_info_mod::update_thermal_properties(fl, tm, dm)
References ftp_refresh_thermal_properties_from_dh.
Referenced by io_restart_mod::restore_thermo_variables_from_restart, eq_energy_mod::solve_energy_eq, eq_scalar_transport_mod::solve_transport_eq.