code_performance_mod
integer, parameter code_performance_mod::cpu_time_code_start
Referenced by call_cpu_time, initialize_chapsim.
integer, parameter code_performance_mod::cpu_time_step_start
Referenced by call_cpu_time, solve_eqs_iteration.
integer, parameter code_performance_mod::cpu_time_iter_start
Referenced by call_cpu_time, burgers_eq_mod::solve_burgers_eq_iteration, solve_eqs_iteration.
integer, parameter code_performance_mod::cpu_time_iter_end
Referenced by call_cpu_time, solve_eqs_iteration.
integer, parameter code_performance_mod::cpu_time_step_end
Referenced by call_cpu_time, solve_eqs_iteration.
integer, parameter code_performance_mod::cpu_time_code_end
Referenced by call_cpu_time, finalise_chapsim, burgers_eq_mod::solve_burgers_eq_iteration.
real(wp), save code_performance_mod::t_code_start
Referenced by call_cpu_time.
real(wp), save code_performance_mod::t_step_start
Referenced by call_cpu_time.
real(wp), save code_performance_mod::t_iter_start
Referenced by call_cpu_time.
real(wp), save code_performance_mod::t_iter_end
Referenced by call_cpu_time.
real(wp), save code_performance_mod::t_step_end
Referenced by call_cpu_time.
real(wp), save code_performance_mod::t_code_end
Referenced by call_cpu_time.
subroutine, private code_performance_mod::convert_sec_to_hms(s, hrs, mins, secs)
References parameters_constant_mod::sixty, precision_mod::wp.
Referenced by call_cpu_time.
subroutine, public code_performance_mod::call_cpu_time(itype, iterfrom, niter, iter)
References convert_sec_to_hms, cpu_time_code_end, cpu_time_code_start, cpu_time_iter_end, cpu_time_iter_start, cpu_time_step_end, cpu_time_step_start, mpi_mod::ierror, typeconvert_mod::int2str, print_debug_mid_msg, print_debug_start_msg, print_error_msg, typeconvert_mod::real2str, t_code_end, t_code_start, t_iter_end, t_iter_start, t_step_end, t_step_start, parameters_constant_mod::zero.
Referenced by finalise_chapsim, initialize_chapsim, burgers_eq_mod::solve_burgers_eq_iteration, solve_eqs_iteration.