continuity_eq_mod
subroutine, public continuity_eq_mod::calculate_drhodt(dm, ddens, ddensm1, ddensm2, drhodt)
To calculate d(\rho)/dt in the continuity eq.
dDens density at the current time step dDensm1 density at the t-1 time step dDensm2 density at the t-2 time step drhodt d(rho)/dt itime the sub-step in RK3
References parameters_constant_mod::half, parameters_constant_mod::itime_ab2, parameters_constant_mod::itime_rk3, parameters_constant_mod::itime_rk3_cn, parameters_constant_mod::two.
Referenced by check_mass_conservation, eq_momentum_mod::solve_poisson, eq_momentum_mod::solve_poisson_x2z.
subroutine, public continuity_eq_mod::get_divergence_vel(ux, uy, uz, div, dm)
To calculate divergence of (rho * u) or divergence of (u)
ux ux or gx uy uy or gy uz uz or gz div div(u) or div(g) d domain
References operations::get_x_1st_derivative_p2c_3d, operations::get_y_1st_derivative_p2c_3d, operations::get_z_1st_derivative_p2c_3d, parameters_constant_mod::zero.
Referenced by check_mass_conservation, eq_momentum_mod::solve_poisson.
subroutine, public continuity_eq_mod::get_divergence_vel_x2z(ux, uy, uz, div_zpencil_ggg, dm)
To calculate divergence of (rho * u) or divergence of (u)
ux ux or gx uy uy or gy uz uz or gz div div(u) or div(g) d domain
References operations::get_x_1st_derivative_p2c_3d, operations::get_y_1st_derivative_p2c_3d, operations::get_z_1st_derivative_p2c_3d, decomp_extended_mod::ypencil_index_lgl2ggl, parameters_constant_mod::zero, decomp_extended_mod::zpencil_index_llg2ggg.
Referenced by eq_momentum_mod::solve_poisson_x2z.
subroutine, public continuity_eq_mod::check_mass_conservation(fl, dm)
To calculate divergence of (rho * u) or divergence of (u)
ux ux or gx uy uy or gy uz uz or gz div div(u) or div(g) d domain
References calculate_drhodt, solver_tools_mod::find_maximum_absvar3d, get_divergence_vel, io_visulisation_mod::write_snapshot_any3darray, wtformat_mod::wrtfmt1e, parameters_constant_mod::zero.
Referenced by flow_thermo_initialiasation::initialize_flow_fields, solve_eqs_iteration.