flow_thermo_initialiasation
subroutine, private flow_thermo_initialiasation::allocate_flow_variables(fl, dm)
Allocate flow and thermal variables.
Scope: mpi called-freq xdomain module all once specified private none NA none NA
References parameters_constant_mod::one, print_debug_end_msg, print_debug_start_msg, parameters_constant_mod::zero.
Referenced by initialize_flow_fields.
subroutine, private flow_thermo_initialiasation::allocate_thermo_variables(tm, dm)
References parameters_constant_mod::one, print_debug_end_msg, print_debug_start_msg, parameters_constant_mod::zero.
Referenced by initialize_thermo_fields.
subroutine, private flow_thermo_initialiasation::generate_random_field(dm, ux, uy, uz, p, lnoise)
Generate a flow profile for Poiseuille flow in channel or pipe.
Scope: mpi called-freq xdomain module all once specified private <br> <br>
References boundary_conditions_mod::apply_bc_velocity, random_number_generation_mod::generate_r_random, random_number_generation_mod::initialize_random_number, parameters_constant_mod::ndim, parameters_constant_mod::one, print_debug_end_msg, print_debug_start_msg, parameters_constant_mod::zero.
Referenced by initialize_flow_fields, initialize_flow_from_given_values, initialize_poiseuille_flow.
subroutine, private flow_thermo_initialiasation::generate_poiseuille_flow_profile(dm, ux_1c1)
Generate a flow profile for Poiseuille flow in channel or pipe.
Scope: mpi called-freq xdomain module all once specified private d domain ux_1c1 u(yc), velocity profile along wall-normal direction
References parameters_constant_mod::half, parameters_constant_mod::icase_annual, parameters_constant_mod::icase_channel, parameters_constant_mod::icase_pipe, parameters_constant_mod::one, parameters_constant_mod::onepfive, print_debug_end_msg, print_debug_mid_msg, parameters_constant_mod::two, parameters_constant_mod::zero.
Referenced by initialize_poiseuille_flow.
subroutine, private flow_thermo_initialiasation::initialize_poiseuille_flow(dm, ux, uy, uz, p, lnoise)
Initialize Poiseuille flow in channel or pipe.
Scope: mpi called-freq xdomain module all once specified private d domain f flow
References boundary_conditions_mod::apply_bc_velocity, files_io_mod::dir_chkp, solver_tools_mod::find_maximum_absvar3d, generate_poiseuille_flow_profile, generate_random_field, solver_tools_mod::get_volumetric_average_3d, print_debug_end_msg, print_debug_mid_msg, wtformat_mod::wrtfmt1e, wtformat_mod::wrtfmt1r, parameters_constant_mod::zero.
Referenced by initialize_flow_fields.
subroutine, private flow_thermo_initialiasation::initialize_flow_from_given_values(dm, ux, uy, uz, p, lnoise, velo)
References boundary_conditions_mod::apply_bc_velocity, generate_random_field, print_debug_end_msg, print_debug_mid_msg, precision_mod::wp, parameters_constant_mod::zero.
Referenced by initialize_flow_fields.
subroutine, public flow_thermo_initialiasation::initialize_flow_fields(fl, dm)
References allocate_flow_variables, continuity_eq_mod::check_mass_conservation, solver_tools_mod::find_maximum_absvar3d, generate_random_field, parameters_constant_mod::icase_burgers, parameters_constant_mod::icase_tgv2d, parameters_constant_mod::icase_tgv3d, parameters_constant_mod::init_function, parameters_constant_mod::init_gvconst, parameters_constant_mod::init_inlet, parameters_constant_mod::init_interpl, parameters_constant_mod::init_poiseuille, parameters_constant_mod::init_random, parameters_constant_mod::init_restart, burgers_eq_mod::initialize_burgers_flow, initialize_flow_from_given_values, initialize_poiseuille_flow, initialize_vortexgreen_2dflow, initialize_vortexgreen_3dflow, parameters_constant_mod::one, print_debug_start_msg, io_restart_mod::read_instantanous_flow_raw_data, io_restart_mod::restore_flow_variables_from_restart, solver_tools_mod::update_re, io_visulisation_mod::write_snapshot_flow, wtformat_mod::wrtfmt1e, parameters_constant_mod::zero.
Referenced by initialize_chapsim.
subroutine, public flow_thermo_initialiasation::initialize_thermo_fields(tm, fl, dm)
References allocate_thermo_variables, eq_energy_mod::calculate_massflux_from_velocity, parameters_constant_mod::init_interpl, parameters_constant_mod::init_restart, thermo_info_mod::initialize_thermal_properties, print_debug_start_msg, io_restart_mod::read_instantanous_thermo_raw_data, io_restart_mod::restore_thermo_variables_from_restart, parameters_constant_mod::zero.
Referenced by initialize_chapsim.
subroutine, private flow_thermo_initialiasation::initialize_vortexgreen_2dflow(dm, ux, uy, uz, p)
Initialize Vortex Green flow.
This subroutine is called locally once. d domain f flow
References parameters_constant_mod::half, print_debug_end_msg, print_debug_mid_msg, parameters_constant_mod::zero.
Referenced by initialize_flow_fields.
subroutine, public flow_thermo_initialiasation::validate_tgv2d_error(fl, dm)
References parameters_constant_mod::half, print_debug_end_msg, print_debug_mid_msg, parameters_constant_mod::quarter, parameters_constant_mod::two, parameters_constant_mod::zero.
subroutine, private flow_thermo_initialiasation::initialize_vortexgreen_3dflow(dm, ux, uy, uz, p)
Initialize Vortex Green flow.
This subroutine is called locally once. d domain f flow
References parameters_constant_mod::half, parameters_constant_mod::one, print_debug_end_msg, print_debug_mid_msg, parameters_constant_mod::sixteen, parameters_constant_mod::two, parameters_constant_mod::zero.
Referenced by initialize_flow_fields.