solver_tools_mod
subroutine, public solver_tools_mod::update_re(iter, fl)
The main code for initializing flow variables This subroutine is called once in Initialize_chapsim.
<br>
References parameters_constant_mod::one.
Referenced by flow_thermo_initialiasation::initialize_flow_fields, burgers_eq_mod::solve_burgers_eq_iteration, solve_eqs_iteration.
subroutine, public solver_tools_mod::update_prgr(fl, tm)
References thermo_info_mod::fluidparam, parameters_constant_mod::gravity, parameters_constant_mod::one, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::solve_burgers_eq_iteration, solve_eqs_iteration.
subroutine, public solver_tools_mod::calculate_xz_mean_yprofile(var, dtmp, n, varxz_work1)
The main code for initializing flow variables.
not changing storage position, exclude b.c. values, for example, developing flow. MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) none NA
References mpi_mod::ierror, mpi_mod::p_col, parameters_constant_mod::zero.
subroutine, public solver_tools_mod::adjust_to_xzmean_zero(var, dtmp, n, varxz)
: MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z)
<br>
subroutine, public solver_tools_mod::check_cfl_diffusion(x2r, rre, dt)
: MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z)
<br>
References parameters_constant_mod::one, print_warning_msg, parameters_constant_mod::two, wtformat_mod::wrtfmt1r.
Referenced by solve_eqs_iteration.
subroutine, public solver_tools_mod::check_cfl_convection(u, v, w, dm)
: to check CFL for convection terms CFL = u^x/dx + v^y/dy + w^z/dz < limit MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z)
<br>
References find_maximum_absvar3d, operations::get_x_midp_p2c_1d, operations::get_y_midp_p2c_1d, operations::get_z_midp_p2c_1d, wtformat_mod::wrtfmt1r, parameters_constant_mod::zero.
Referenced by solve_eqs_iteration.
subroutine, public solver_tools_mod::get_volumetric_average_3d(is_ynp, ibcy, fbcy, dm, dtmp, var, fo_work)
: to calculate: fo = \int_1^nx \int_ This is based only y-direction stretching.
TodoHere is 2nd order Trapezoid Method. Need to improve! Check! Scope: mpi called-freq xdomain module all needed specified pubic MPI : default x-pencil working in : y-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 <br>
References operations::get_y_midp_c2p_3d, operations::get_y_midp_p2c_3d, parameters_constant_mod::half, mpi_mod::ierror, parameters_constant_mod::one, print_debug_start_msg, wtformat_mod::wrtfmt1r, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs, flow_thermo_initialiasation::initialize_poiseuille_flow, io_restart_mod::restore_flow_variables_from_restart, io_monitor_mod::write_monitor_total.
subroutine, public solver_tools_mod::find_maximum_absvar3d(var, str, fmt)
References mpi_mod::ierror, parameters_constant_mod::maxvelo, precision_mod::mpi_real_wp, parameters_constant_mod::zero.
Referenced by check_cfl_convection, continuity_eq_mod::check_mass_conservation, flow_thermo_initialiasation::initialize_flow_fields, flow_thermo_initialiasation::initialize_poiseuille_flow, io_restart_mod::restore_flow_variables_from_restart, solve_eqs_iteration.