operations
real(wp), dimension(5, 3, 6), save, public operations::d1fc2c
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save, public operations::d1rc2c
Referenced by get_x_1st_derivative_c2c_1d, get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, get_z_1st_derivative_c2c_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save operations::d1fp2p
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save operations::d1rp2p
Referenced by get_x_1st_derivative_p2p_1d, get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, get_z_1st_derivative_p2p_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save, public operations::d1fc2p
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save, public operations::d1rc2p
Referenced by get_x_1st_derivative_c2p_1d, get_y_1st_derivative_c2p_1d, get_z_1st_derivative_c2p_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save operations::d1fp2c
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save operations::d1rp2c
Referenced by get_x_1st_derivative_p2c_1d, get_y_1st_derivative_p2c_1d, get_z_1st_derivative_p2c_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save, public operations::d2fc2c
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save, public operations::d2rc2c
Referenced by get_x_2nd_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, get_z_2nd_derivative_c2c_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save operations::d2fp2p
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save operations::d2rp2p
Referenced by get_x_2nd_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, get_z_2nd_derivative_p2p_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save operations::m1fp2c
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save operations::m1rp2c
Referenced by get_x_midp_p2c_1d, get_y_midp_p2c_1d, get_z_midp_p2c_1d, prepare_compact_coefficients.
real(wp), dimension(5, 3, 6), save, public operations::m1fc2p
Referenced by prepare_compact_coefficients, prepare_lhs_coeffs_for_operations.
real(wp), dimension(5, 4, 6), save, public operations::m1rc2p
Referenced by get_x_midp_c2p_1d, get_y_midp_c2p_1d, get_z_midp_c2p_1d, prepare_compact_coefficients.
type(t_xtdma_lhs), dimension(:), allocatable operations::xtdma_lhs
Referenced by get_x_1st_derivative_c2c_1d, get_x_1st_derivative_c2p_1d, get_x_1st_derivative_p2c_1d, get_x_1st_derivative_p2p_1d, get_x_2nd_derivative_c2c_1d, get_x_2nd_derivative_p2p_1d, get_x_midp_c2p_1d, get_x_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1y_p2p
Referenced by get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1y_p2p
Referenced by get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1y_p2p
Referenced by get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1y_p2p
Referenced by get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1y_c2c
Referenced by get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1y_c2c
Referenced by get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1y_c2c
Referenced by get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1y_c2c
Referenced by get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1y_p2c
Referenced by get_y_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1y_p2c
Referenced by get_y_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1y_p2c
Referenced by get_y_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1y_p2c
Referenced by get_y_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1y_c2p
Referenced by get_y_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1y_c2p
Referenced by get_y_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1y_c2p
Referenced by get_y_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1y_c2p
Referenced by get_y_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad2y_p2p
Referenced by get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd2y_p2p
Referenced by get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd2y_p2p
Referenced by get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd2y_p2p
Referenced by get_y_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad2y_c2c
Referenced by get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd2y_c2c
Referenced by get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd2y_c2c
Referenced by get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd2y_c2c
Referenced by get_y_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::am1y_p2c
Referenced by get_y_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bm1y_p2c
Referenced by get_y_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cm1y_p2c
Referenced by get_y_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dm1y_p2c
Referenced by get_y_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::am1y_c2p
Referenced by get_y_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bm1y_c2p
Referenced by get_y_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cm1y_c2p
Referenced by get_y_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dm1y_c2p
Referenced by get_y_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1z_p2p
Referenced by get_z_1st_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1z_p2p
Referenced by get_z_1st_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1z_p2p
Referenced by get_z_1st_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1z_p2p
Referenced by get_z_1st_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1z_c2c
Referenced by get_z_1st_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1z_c2c
Referenced by get_z_1st_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1z_c2c
Referenced by get_z_1st_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1z_c2c
Referenced by get_z_1st_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1z_p2c
Referenced by get_z_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1z_p2c
Referenced by get_z_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1z_p2c
Referenced by get_z_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1z_p2c
Referenced by get_z_1st_derivative_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad1z_c2p
Referenced by get_z_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd1z_c2p
Referenced by get_z_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd1z_c2p
Referenced by get_z_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd1z_c2p
Referenced by get_z_1st_derivative_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad2z_p2p
Referenced by get_z_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd2z_p2p
Referenced by get_z_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd2z_p2p
Referenced by get_z_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd2z_p2p
Referenced by get_z_2nd_derivative_p2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::ad2z_c2c
Referenced by get_z_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bd2z_c2c
Referenced by get_z_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cd2z_c2c
Referenced by get_z_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dd2z_c2c
Referenced by get_z_2nd_derivative_c2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::am1z_p2c
Referenced by get_z_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bm1z_p2c
Referenced by get_z_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cm1z_p2c
Referenced by get_z_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dm1z_p2c
Referenced by get_z_midp_p2c_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::am1z_c2p
Referenced by get_z_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::bm1z_c2p
Referenced by get_z_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::cm1z_c2p
Referenced by get_z_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
real(wp), dimension(:, :, :), allocatable operations::dm1z_c2p
Referenced by get_z_midp_c2p_1d, prepare_lhs_coeffs_for_operations.
subroutine, private operations::prepare_compact_coefficients(iaccu)
Assigned the cooefficients for the compact schemes Scope: mpi called-freq xdomain module all once specified private.
iaccu the accuracy given by user
References d1fc2c, d1fc2p, d1fp2c, d1fp2p, d1rc2c, d1rc2p, d1rp2c, d1rp2p, d2fc2c, d2fp2p, d2rc2c, d2rp2p, parameters_constant_mod::eight, parameters_constant_mod::eighth, parameters_constant_mod::eleven, parameters_constant_mod::fifteen, parameters_constant_mod::fifty, parameters_constant_mod::five, parameters_constant_mod::four, parameters_constant_mod::fourteen, parameters_constant_mod::fourtyfive, parameters_constant_mod::half, parameters_constant_mod::iaccu_cd2, parameters_constant_mod::iaccu_cd4, parameters_constant_mod::iaccu_cp4, parameters_constant_mod::iaccu_cp6, parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, m1fc2p, m1fp2c, m1rc2p, m1rp2c, parameters_constant_mod::nine, parameters_constant_mod::one, parameters_constant_mod::one_third, parameters_constant_mod::onepfive, print_debug_end_msg, print_debug_start_msg, parameters_constant_mod::quarter, parameters_constant_mod::seven, parameters_constant_mod::seventeen, parameters_constant_mod::six, parameters_constant_mod::sixteen, parameters_constant_mod::sixtythree, parameters_constant_mod::sixtytwo, parameters_constant_mod::ten, parameters_constant_mod::thirteen, parameters_constant_mod::thirtytwo, parameters_constant_mod::three, parameters_constant_mod::twelve, parameters_constant_mod::twentyfive, parameters_constant_mod::twentyseven, parameters_constant_mod::twentysix, parameters_constant_mod::twentythree, parameters_constant_mod::twentytwo, parameters_constant_mod::two, parameters_constant_mod::two_third, parameters_constant_mod::twopfive, parameters_constant_mod::zero, parameters_constant_mod::zpone, parameters_constant_mod::zptwo.
Referenced by prepare_lhs_coeffs_for_operations.
subroutine, private operations::buildup_tdma_lhs_array(n, is_periodic, coeff, a, b, c, d)
Assigning the sparse matrix in the LHS of the compact scheme, and calculating the geometry-only dependent variables for the TDMA scheme.
This subroutine is called once locally. n the number of unknown array bc the boundary condition at two ends of the unknown coeff the basic TDMA coefficients defined above. a the coefficients for TDMA b a_i * x_(i-1) + b_i * x_(i) + c_i * x_(i+1) c = RHS d An assisting coeffients for the TDMA scheme.
References parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, tridiagonal_matrix_algorithm::preprocess_tdma_coeffs, parameters_constant_mod::zero.
Referenced by prepare_lhs_coeffs_for_operations.
subroutine, public operations::prepare_lhs_coeffs_for_operations
Preparing coefficients for TDMA calculation.
Scope: mpi called-freq xdomain all once all
References ad1y_c2c, ad1y_c2p, ad1y_p2c, ad1y_p2p, ad1z_c2c, ad1z_c2p, ad1z_p2c, ad1z_p2p, ad2y_c2c, ad2y_p2p, ad2z_c2c, ad2z_p2p, am1y_c2p, am1y_p2c, am1z_c2p, am1z_p2c, bd1y_c2c, bd1y_c2p, bd1y_p2c, bd1y_p2p, bd1z_c2c, bd1z_c2p, bd1z_p2c, bd1z_p2p, bd2y_c2c, bd2y_p2p, bd2z_c2c, bd2z_p2p, bm1y_c2p, bm1y_p2c, bm1z_c2p, bm1z_p2c, buildup_tdma_lhs_array, cd1y_c2c, cd1y_c2p, cd1y_p2c, cd1y_p2p, cd1z_c2c, cd1z_c2p, cd1z_p2c, cd1z_p2p, cd2y_c2c, cd2y_p2p, cd2z_c2c, cd2z_p2p, cm1y_c2p, cm1y_p2c, cm1z_c2p, cm1z_p2c, d1fc2c, d1fc2p, d1fp2c, d1fp2p, d2fc2c, d2fp2p, dd1y_c2c, dd1y_c2p, dd1y_p2c, dd1y_p2p, dd1z_c2c, dd1z_c2p, dd1z_p2c, dd1z_p2p, dd2y_c2c, dd2y_p2p, dd2z_c2c, dd2z_p2p, dm1y_c2p, dm1y_p2c, dm1z_c2p, dm1z_p2c, vars_df_mod::domain, m1fc2p, m1fp2c, mpi_mod::nxdomain, prepare_compact_coefficients, xtdma_lhs, parameters_constant_mod::zero.
Referenced by initialize_chapsim.
subroutine, private operations::prepare_tdma_interp_p2c_rhs_array(fi, fo, nc, coeff, ibc)
Preparing the RHS array for the TDMA algorithm for interpolation. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the interpolation.
Scope: mpi called-freq xdomain module given pencil needed specified private index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is nc ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::zero.
Referenced by get_x_midp_p2c_1d, get_y_midp_p2c_1d, get_z_midp_p2c_1d.
subroutine, private operations::prepare_tdma_interp_c2p_rhs_array(fi, fo, np, coeff, ibc, fbc)
Preparing the RHS array for the TDMA algorithm for interpolation. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the interpolation.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is np ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, print_error_msg, parameters_constant_mod::zero.
Referenced by get_x_midp_c2p_1d, get_y_midp_c2p_1d, get_z_midp_c2p_1d.
subroutine, private operations::prepare_tdma_1deri_c2c_rhs_array(fi, fo, nc, coeff, dd, ibc, fbc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is np ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, print_error_msg, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_c2c_1d, get_y_1st_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, get_z_1st_derivative_c2c_1d.
subroutine, private operations::prepare_tdma_1deri_p2p_rhs_array(fi, fo, np, coeff, dd, ibc, fbc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is np ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, print_error_msg, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_p2p_1d, get_y_1st_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, get_z_1st_derivative_p2p_1d.
subroutine, private operations::prepare_tdma_1deri_c2p_rhs_array(fi, fo, np, coeff, dd, ibc, fbc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is np ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, print_error_msg, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_c2p_1d, get_y_1st_derivative_c2p_1d, get_z_1st_derivative_c2p_1d.
subroutine, private operations::prepare_tdma_1deri_p2c_rhs_array(fi, fo, nc, coeff, dd, ibc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is np ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_p2c_1d, get_y_1st_derivative_p2c_1d, get_z_1st_derivative_p2c_1d.
subroutine, private operations::prepare_tdma_2deri_c2c_rhs_array(fi, fo, nc, coeff, dd, ibc, fbc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is nc ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, print_error_msg, parameters_constant_mod::two, parameters_constant_mod::zero.
Referenced by get_x_2nd_derivative_c2c_1d, get_y_2nd_derivative_c2c_1d, get_z_2nd_derivative_c2c_1d.
subroutine, private operations::prepare_tdma_2deri_p2p_rhs_array(fi, fo, np, coeff, dd, ibc)
Preparing the RHS array for the TDMA algorithm for 1st derivative. This subroutine is called repeatly to update the RHS of the TDMA algorithm for the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified private Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__.__|__.__|__.__|__.__|__.__ j-2 j-1 j j+1 j+2 n the number of unknowns, here is nc ibc the b.c. type at two ends of the unknown array fbc the b.c. values for the given ibc inbr the neibouring index of 4 bc nodes coeff the defined TDMA coefficients dd 1/spacing, ie. 1/dx, 1/dy, 1/dz fi the input variable to build up the RHS array fo the output RHS array
References parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_intrpl, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::two, parameters_constant_mod::zero.
Referenced by get_x_2nd_derivative_p2p_1d, get_y_2nd_derivative_p2p_1d, get_z_2nd_derivative_p2p_1d.
subroutine, public operations::get_x_midp_c2p_1d(fi, fo, dm, ibc, fbc)
To caculate the mid-point interpolation in 1D. This subroutine is called as required to get the mid-point interpolation.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References parameters_constant_mod::ibc_dirichlet, m1rc2p, prepare_tdma_interp_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by eq_energy_mod::calculate_massflux_from_velocity, get_x_midp_c2p_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_x_midp_p2c_1d(fi, fo, dm, ibc)
References m1rp2c, prepare_tdma_interp_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by solver_tools_mod::check_cfl_convection, get_x_midp_p2c_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_y_midp_c2p_1d(fi, fo, dm, ibc, fbc)
References am1y_c2p, bm1y_c2p, cm1y_c2p, dm1y_c2p, parameters_constant_mod::ibc_dirichlet, m1rc2p, prepare_tdma_interp_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by eq_energy_mod::calculate_massflux_from_velocity, get_y_midp_c2p_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_y_midp_p2c_1d(fi, fo, dm, ibc)
References am1y_p2c, bm1y_p2c, cm1y_p2c, dm1y_p2c, m1rp2c, prepare_tdma_interp_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by solver_tools_mod::check_cfl_convection, get_y_midp_p2c_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_z_midp_c2p_1d(fi, fo, dm, ibc, fbc)
References am1z_c2p, bm1z_c2p, cm1z_c2p, dm1z_c2p, parameters_constant_mod::ibc_dirichlet, m1rc2p, prepare_tdma_interp_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by eq_energy_mod::calculate_massflux_from_velocity, get_z_midp_c2p_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_z_midp_p2c_1d(fi, fo, dm, ibc)
References am1z_p2c, bm1z_p2c, cm1z_p2c, dm1z_p2c, m1rp2c, prepare_tdma_interp_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by solver_tools_mod::check_cfl_convection, get_z_midp_p2c_3d, test_operations_mod::test_interpolation.
subroutine, public operations::get_x_1st_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
To caculate the 1st derivative in 1D. This subroutine is called as required to get the 1st derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References d1rc2c, prepare_tdma_1deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_c2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_x_1st_derivative_p2p_1d(fi, fo, dm, ibc, fbc)
References d1rp2p, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_p2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_p2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_x_1st_derivative_c2p_1d(fi, fo, dm, ibc, fbc)
References d1rc2p, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_c2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_x_1st_derivative_p2c_1d(fi, fo, dm, ibc)
References d1rp2c, prepare_tdma_1deri_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_1st_derivative_p2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_y_1st_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
References ad1y_c2c, bd1y_c2c, cd1y_c2c, d1rc2c, dd1y_c2c, prepare_tdma_1deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_1st_derivative_c2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_y_1st_derivative_p2p_1d(fi, fo, dm, ibc, fbc)
References ad1y_p2p, bd1y_p2p, cd1y_p2p, d1rp2p, dd1y_p2p, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_p2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_1st_derivative_p2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_y_1st_derivative_c2p_1d(fi, fo, dm, ibc, fbc)
References ad1y_c2p, bd1y_c2p, cd1y_c2p, d1rc2p, dd1y_c2p, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_1st_derivative_c2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_y_1st_derivative_p2c_1d(fi, fo, dm, ibc)
References ad1y_p2c, bd1y_p2c, cd1y_p2c, d1rp2c, dd1y_p2c, prepare_tdma_1deri_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_1st_derivative_p2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_z_1st_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
References ad1z_c2c, bd1z_c2c, cd1z_c2c, d1rc2c, dd1z_c2c, prepare_tdma_1deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_1st_derivative_c2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_z_1st_derivative_p2p_1d(fi, fo, dm, ibc, fbc)
References ad1z_p2p, bd1z_p2p, cd1z_p2p, d1rp2p, dd1z_p2p, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_p2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_1st_derivative_p2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_z_1st_derivative_c2p_1d(fi, fo, dm, ibc, fbc)
References ad1z_c2p, bd1z_c2p, cd1z_c2p, d1rc2p, dd1z_c2p, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, prepare_tdma_1deri_c2p_rhs_array, print_error_msg, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_1st_derivative_c2p_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_z_1st_derivative_p2c_1d(fi, fo, dm, ibc)
References ad1z_p2c, bd1z_p2c, cd1z_p2c, d1rp2c, dd1z_p2c, prepare_tdma_1deri_p2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_1st_derivative_p2c_3d, test_operations_mod::test_1st_derivative.
subroutine, public operations::get_x_2nd_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
To caculate the 2nd derivative in 1D. This subroutine is called as required to get the 2nd derivative.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References d2rc2c, prepare_tdma_2deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_2nd_derivative_c2c_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_x_2nd_derivative_p2p_1d(fi, fo, dm, ibc)
References d2rp2p, prepare_tdma_2deri_p2p_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, xtdma_lhs, parameters_constant_mod::zero.
Referenced by get_x_2nd_derivative_p2p_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_y_2nd_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
References ad1y_c2c, ad2y_c2c, bd1y_c2c, bd2y_c2c, cd1y_c2c, cd2y_c2c, d1rc2c, d2rc2c, dd1y_c2c, dd2y_c2c, prepare_tdma_1deri_c2c_rhs_array, prepare_tdma_2deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_2nd_derivative_c2c_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_y_2nd_derivative_p2p_1d(fi, fo, dm, ibc)
References ad1y_p2p, ad2y_p2p, bd1y_p2p, bd2y_p2p, cd1y_p2p, cd2y_p2p, d1rp2p, d2rp2p, dd1y_p2p, dd2y_p2p, prepare_tdma_1deri_p2p_rhs_array, prepare_tdma_2deri_p2p_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_y_2nd_derivative_p2p_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_z_2nd_derivative_c2c_1d(fi, fo, dm, ibc, fbc)
References ad2z_c2c, bd2z_c2c, cd2z_c2c, d2rc2c, dd2z_c2c, prepare_tdma_2deri_c2c_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_2nd_derivative_c2c_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_z_2nd_derivative_p2p_1d(fi, fo, dm, ibc)
References ad2z_p2p, bd2z_p2p, cd2z_p2p, d2rp2p, dd2z_p2p, prepare_tdma_2deri_p2p_rhs_array, tridiagonal_matrix_algorithm::solve_tdma, parameters_constant_mod::zero.
Referenced by get_z_2nd_derivative_p2p_3d, test_operations_mod::test_2nd_derivative.
subroutine, public operations::get_x_midp_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
To caculate the mid-point interpolation in 3D.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References get_x_midp_c2p_1d, parameters_constant_mod::ibc_dirichlet, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs.
subroutine, public operations::get_x_midp_p2c_3d(fi3d, fo3d, dm, ibc)
References get_x_midp_p2c_1d, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs, eq_momentum_mod::compute_momentum_rhs, statistics_mod::update_statistics_flow, io_monitor_mod::write_monitor_total, io_visulisation_mod::write_snapshot_any3darray, io_visulisation_mod::write_snapshot_flow.
subroutine, public operations::get_y_midp_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_y_midp_c2p_1d, parameters_constant_mod::ibc_dirichlet, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, solver_tools_mod::get_volumetric_average_3d.
subroutine, public operations::get_y_midp_p2c_3d(fi3d, fo3d, dm, ibc)
References get_y_midp_p2c_1d, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs, eq_momentum_mod::compute_momentum_rhs, solver_tools_mod::get_volumetric_average_3d, statistics_mod::update_statistics_flow, io_monitor_mod::write_monitor_total, io_visulisation_mod::write_snapshot_any3darray, io_visulisation_mod::write_snapshot_flow.
subroutine, public operations::get_z_midp_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_z_midp_c2p_1d, parameters_constant_mod::ibc_dirichlet, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs.
subroutine, public operations::get_z_midp_p2c_3d(fi3d, fo3d, dm, ibc)
References get_z_midp_p2c_1d, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs, statistics_mod::update_statistics_flow, io_monitor_mod::write_monitor_total, io_visulisation_mod::write_snapshot_any3darray, io_visulisation_mod::write_snapshot_flow.
subroutine, public operations::get_x_1st_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
To caculate the 1st-deriviate in 3D.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References get_x_1st_derivative_c2c_1d, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_x_1st_derivative_p2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_x_1st_derivative_p2p_1d, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_x_1st_derivative_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_x_1st_derivative_c2p_1d, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs, eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, eq_momentum_mod::correct_massflux.
subroutine, public operations::get_x_1st_derivative_p2c_3d(fi3d, fo3d, dm, ibc)
References get_x_1st_derivative_p2c_1d, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs, eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, continuity_eq_mod::get_divergence_vel, continuity_eq_mod::get_divergence_vel_x2z.
subroutine, public operations::get_y_1st_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
References get_y_1st_derivative_c2c_1d, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_y_1st_derivative_p2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_y_1st_derivative_p2p_1d, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_y_1st_derivative_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_y_1st_derivative_c2p_1d, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs, eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, eq_momentum_mod::correct_massflux.
subroutine, public operations::get_y_1st_derivative_p2c_3d(fi3d, fo3d, dm, ibc)
References get_y_1st_derivative_p2c_1d, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, continuity_eq_mod::get_divergence_vel, continuity_eq_mod::get_divergence_vel_x2z.
subroutine, public operations::get_z_1st_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
References get_z_1st_derivative_c2c_1d, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_z_1st_derivative_p2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_z_1st_derivative_p2p_1d, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_momentum_mod::compute_momentum_rhs.
subroutine, public operations::get_z_1st_derivative_c2p_3d(fi3d, fo3d, dm, ibc, fbc)
References get_z_1st_derivative_c2p_1d, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, print_error_msg, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, eq_momentum_mod::correct_massflux.
subroutine, public operations::get_z_1st_derivative_p2c_3d(fi3d, fo3d, dm, ibc)
References get_z_1st_derivative_p2c_1d, parameters_constant_mod::zero.
Referenced by eq_energy_mod::compute_energy_rhs, eq_momentum_mod::compute_momentum_rhs, eq_scalar_transport_mod::compute_transport_rhs, continuity_eq_mod::get_divergence_vel, continuity_eq_mod::get_divergence_vel_x2z.
subroutine, public operations::get_x_2nd_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
To caculate the 2nd-deriviate in 3D.
Scope: mpi called-freq xdomain module in-given pencil needed specified pubic ixsub x-subdomain index ibc bc type fbc bc value inbr the neibouring index of 4 bc nodes fi the input array of original variable fo the output array of interpolated variable
References get_x_2nd_derivative_c2c_1d, parameters_constant_mod::zero.
subroutine, public operations::get_x_2nd_derivative_p2p_3d(fi3d, fo3d, dm, ibc)
References get_x_2nd_derivative_p2p_1d, parameters_constant_mod::zero.
subroutine, public operations::get_y_2nd_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
References get_y_2nd_derivative_c2c_1d, parameters_constant_mod::zero.
subroutine, public operations::get_y_2nd_derivative_p2p_3d(fi3d, fo3d, dm, ibc)
References get_y_2nd_derivative_p2p_1d, parameters_constant_mod::zero.
Referenced by burgers_eq_mod::compute_burgers_rhs.
subroutine, public operations::get_z_2nd_derivative_c2c_3d(fi3d, fo3d, dm, ibc, fbc)
References get_z_2nd_derivative_c2c_1d, parameters_constant_mod::zero.
subroutine, public operations::get_z_2nd_derivative_p2p_3d(fi3d, fo3d, dm, ibc)
References get_z_2nd_derivative_p2p_1d, parameters_constant_mod::zero.