test_operations_mod
subroutine, public test_operations_mod::test_interpolation(dm)
To test this subroutine for mid-point interpolation.
This subroutine is called in Test_algorithms. Define the logicals to choose which test section is required. d domain
References operations::get_x_midp_c2p_1d, operations::get_x_midp_p2c_1d, operations::get_y_midp_c2p_1d, operations::get_y_midp_p2c_1d, operations::get_z_midp_c2p_1d, operations::get_z_midp_p2c_1d, parameters_constant_mod::half, parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::one, parameters_constant_mod::one_third, parameters_constant_mod::pi, parameters_constant_mod::three, parameters_constant_mod::two, parameters_constant_mod::twopi, parameters_constant_mod::zero.
Referenced by test_algorithms.
subroutine, public test_operations_mod::test_1st_derivative(dm)
To test this subroutine for mid-point interpolation.
This subroutine is called in Test_algorithms. Define the logicals to choose which test section is required. d domain
References operations::get_x_1st_derivative_c2c_1d, operations::get_x_1st_derivative_c2p_1d, operations::get_x_1st_derivative_p2c_1d, operations::get_x_1st_derivative_p2p_1d, operations::get_y_1st_derivative_c2c_1d, operations::get_y_1st_derivative_c2p_1d, operations::get_y_1st_derivative_p2c_1d, operations::get_y_1st_derivative_p2p_1d, operations::get_z_1st_derivative_c2c_1d, operations::get_z_1st_derivative_c2p_1d, operations::get_z_1st_derivative_p2c_1d, operations::get_z_1st_derivative_p2p_1d, parameters_constant_mod::half, parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::one, parameters_constant_mod::one_third, parameters_constant_mod::pi, parameters_constant_mod::three, parameters_constant_mod::two, parameters_constant_mod::twopi, parameters_constant_mod::zero.
Referenced by test_algorithms.
subroutine, public test_operations_mod::test_2nd_derivative(dm)
To test this subroutine for mid-point interpolation.
This subroutine is called in Test_algorithms. Define the logicals to choose which test section is required. d domain
References operations::get_x_2nd_derivative_c2c_1d, operations::get_x_2nd_derivative_p2p_1d, operations::get_y_2nd_derivative_c2c_1d, operations::get_y_2nd_derivative_p2p_1d, operations::get_z_2nd_derivative_c2c_1d, operations::get_z_2nd_derivative_p2p_1d, parameters_constant_mod::half, parameters_constant_mod::ibc_asymmetric, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_neumann, parameters_constant_mod::ibc_periodic, parameters_constant_mod::ibc_symmetric, parameters_constant_mod::one, parameters_constant_mod::one_third, parameters_constant_mod::pi, parameters_constant_mod::three, parameters_constant_mod::two, parameters_constant_mod::twopi, parameters_constant_mod::zero.
Referenced by test_algorithms.