io_visulisation_mod
character(len=*), parameter io_visulisation_mod::io_name
Referenced by write_field.
integer, parameter io_visulisation_mod::xdmf_header
Referenced by write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_headerfooter, write_snapshot_thermo, write_snapshot_thermo_stat.
integer, parameter io_visulisation_mod::xdmf_footer
Referenced by write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_headerfooter, write_snapshot_thermo, write_snapshot_thermo_stat.
integer, parameter io_visulisation_mod::plane_average
Referenced by write_field.
character(6), parameter io_visulisation_mod::scalar
Referenced by write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_thermo, write_snapshot_thermo_stat.
character(6), parameter io_visulisation_mod::vector
character(6), parameter io_visulisation_mod::tensor
character(4), parameter io_visulisation_mod::cell
Referenced by write_field, write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_thermo, write_snapshot_thermo_stat.
character(4), parameter io_visulisation_mod::node
Referenced by write_field.
integer, dimension(:, :), allocatable io_visulisation_mod::nnd_visu
Referenced by write_field, write_snapshot_headerfooter, write_snapshot_ini.
integer, dimension(:, :), allocatable io_visulisation_mod::ncl_visu
Referenced by write_field, write_snapshot_ini.
real(wp), dimension(:), allocatable io_visulisation_mod::xp
Referenced by write_snapshot_headerfooter, write_snapshot_ini.
real(wp), dimension(:), allocatable io_visulisation_mod::yp
Referenced by write_snapshot_headerfooter, write_snapshot_ini.
real(wp), dimension(:), allocatable io_visulisation_mod::zp
Referenced by write_snapshot_headerfooter, write_snapshot_ini.
character(6) io_visulisation_mod::svisudim
Referenced by write_field, write_snapshot_headerfooter, write_snapshot_ini.
subroutine, public io_visulisation_mod::write_snapshot_ini(dm)
References files_io_mod::dir_visu, io_tools_mod::generate_pathfile_name, io_tools_mod::ivisudim_1d_xza, io_tools_mod::ivisudim_2d_xa, io_tools_mod::ivisudim_2d_ya, io_tools_mod::ivisudim_2d_za, io_tools_mod::ivisudim_3d, parameters_constant_mod::maxp, ncl_visu, nnd_visu, svisudim, precision_mod::wp, xp, yp, zp.
Referenced by domain_decomposition_mod::buildup_mpi_domain_decomposition.
subroutine, private io_visulisation_mod::write_snapshot_headerfooter(dm, visuname, iheadfoot, iter)
References files_io_mod::dir_visu, io_tools_mod::generate_pathfile_name, parameters_constant_mod::maxp, nnd_visu, svisudim, xdmf_footer, xdmf_header, xp, yp, zp.
Referenced by write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_thermo, write_snapshot_thermo_stat.
subroutine, private io_visulisation_mod::write_field(dm, var, dtmp, varname, visuname, attributetype, centring, iter)
References cell, files_io_mod::dir_data, files_io_mod::dir_visu, io_tools_mod::generate_file_name, io_tools_mod::generate_pathfile_name, io_name, decomp_operation_mod::is_decomp_same, io_tools_mod::ivisudim_1d_xza, io_tools_mod::ivisudim_3d, ncl_visu, nnd_visu, node, plane_average, print_error_msg, svisudim, io_tools_mod::x_pencil.
Referenced by write_snapshot_any3darray, write_snapshot_flow, write_snapshot_flow_stat, write_snapshot_thermo, write_snapshot_thermo_stat.
subroutine, public io_visulisation_mod::write_snapshot_flow(fl, dm)
References cell, operations::get_x_midp_p2c_3d, operations::get_y_midp_p2c_3d, operations::get_z_midp_p2c_3d, scalar, write_field, write_snapshot_headerfooter, xdmf_footer, xdmf_header.
Referenced by flow_thermo_initialiasation::initialize_flow_fields, solve_eqs_iteration.
subroutine, public io_visulisation_mod::write_snapshot_thermo(tm, dm)
References cell, scalar, write_field, write_snapshot_headerfooter, xdmf_footer, xdmf_header.
Referenced by solve_eqs_iteration.
subroutine, public io_visulisation_mod::write_snapshot_flow_stat(fl, dm)
References cell, scalar, write_field, write_snapshot_headerfooter, xdmf_footer, xdmf_header.
Referenced by solve_eqs_iteration.
subroutine, public io_visulisation_mod::write_snapshot_thermo_stat(tm, dm)
References cell, scalar, write_field, write_snapshot_headerfooter, xdmf_footer, xdmf_header.
Referenced by solve_eqs_iteration.
subroutine, public io_visulisation_mod::write_snapshot_any3darray(var, varname, visuname, dtmp, dm, iter)
References cell, operations::get_x_midp_p2c_3d, operations::get_y_midp_p2c_3d, operations::get_z_midp_p2c_3d, decomp_operation_mod::is_decomp_same, print_error_msg, scalar, write_field, write_snapshot_headerfooter, xdmf_footer, xdmf_header.
Referenced by domain_decomposition_mod::buildup_mpi_domain_decomposition, continuity_eq_mod::check_mass_conservation.