eq_momentum_mod
subroutine, private eq_momentum_mod::calculate_momentum_fractional_step(rhs0, rhs1, rhs1_pfc, dtmp, dm, isub)
To calcuate the convection and diffusion terms in rhs of momentum eq.
This subroutine is called everytime when calcuting the rhs of momentum eqs. rhs0 the last iteration rhs rhs1 the current iteration rhs rhs1_semi the semi-implicit term isub the RK iteration to get correct Coefficient
Referenced by compute_momentum_rhs.
subroutine, private eq_momentum_mod::compute_momentum_rhs(fl, dm, isub)
To calcuate all rhs of momentum eq.
This subroutine is called everytime when calcuting the rhs of momentum eqs. f flow field d domain isub the RK iteration to get correct Coefficient
References calculate_momentum_fractional_step, solver_tools_mod::get_volumetric_average_3d, operations::get_x_1st_derivative_c2c_3d, operations::get_x_1st_derivative_c2p_3d, operations::get_x_1st_derivative_p2c_3d, operations::get_x_1st_derivative_p2p_3d, operations::get_x_midp_c2p_3d, operations::get_x_midp_p2c_3d, operations::get_y_1st_derivative_c2c_3d, operations::get_y_1st_derivative_c2p_3d, operations::get_y_1st_derivative_p2c_3d, operations::get_y_1st_derivative_p2p_3d, operations::get_y_midp_c2p_3d, operations::get_y_midp_p2c_3d, operations::get_z_1st_derivative_c2c_3d, operations::get_z_1st_derivative_c2p_3d, operations::get_z_1st_derivative_p2c_3d, operations::get_z_1st_derivative_p2p_3d, operations::get_z_midp_c2p_3d, operations::get_z_midp_p2c_3d, parameters_constant_mod::half, parameters_constant_mod::idrvf_x_cf, parameters_constant_mod::idrvf_x_massflux, parameters_constant_mod::idrvf_z_cf, parameters_constant_mod::idrvf_z_massflux, parameters_constant_mod::one_third, print_debug_start_msg, parameters_constant_mod::two, parameters_constant_mod::two_third, parameters_constant_mod::zero.
Referenced by solve_momentum_eq.
subroutine, private eq_momentum_mod::correct_massflux(ux, uy, uz, phi_ccc, dm, isub)
References operations::get_x_1st_derivative_c2p_3d, operations::get_y_1st_derivative_c2p_3d, operations::get_z_1st_derivative_c2p_3d, print_debug_mid_msg, parameters_constant_mod::zero.
Referenced by solve_momentum_eq.
subroutine, private eq_momentum_mod::solve_poisson(fl, dm, isub)
References continuity_eq_mod::calculate_drhodt, continuity_eq_mod::get_divergence_vel, decomp_2d_poisson::poisson, print_debug_mid_msg, print_debug_start_msg, parameters_constant_mod::zero, decomp_extended_mod::zpencil_index_ggg2llg, decomp_extended_mod::zpencil_index_llg2ggg.
Referenced by solve_momentum_eq.
subroutine, private eq_momentum_mod::solve_poisson_x2z(fl, dm, isub)
References continuity_eq_mod::calculate_drhodt, continuity_eq_mod::get_divergence_vel_x2z, decomp_2d_poisson::poisson, parameters_constant_mod::zero, decomp_extended_mod::zpencil_index_ggg2llg, decomp_extended_mod::zpencil_index_llg2ggg.
subroutine, public eq_momentum_mod::solve_momentum_eq(fl, dm, isub)
To update the provisional u or rho u.
fl flow field dm domain isub RK sub-iteration
References boundary_conditions_mod::apply_bc_velocity, compute_momentum_rhs, correct_massflux, print_debug_mid_msg, print_error_msg, solve_poisson.
Referenced by solve_eqs_iteration.