random_number_generation_mod
subroutine, public random_number_generation_mod::initialize_random_number(seed)
Referenced by flow_thermo_initialiasation::generate_random_field.
subroutine, public random_number_generation_mod::generate_rvec_random(alo, ahi, n, a)
References generate_r_random.
subroutine, public random_number_generation_mod::generate_r_random(rlo, rhi, r)
Referenced by flow_thermo_initialiasation::generate_random_field, generate_rvec_random.