burgers_eq_mod
integer, parameter burgers_eq_mod::icase_burgers1d
Referenced by initialize_burgers_flow.
integer, parameter burgers_eq_mod::icase_burgers1d_viscous
Referenced by compute_burgers_rhs, initialize_burgers_flow, validate_burgers_error.
integer, parameter burgers_eq_mod::icase_burgers1d_inviscid
Referenced by compute_burgers_rhs, initialize_burgers_flow, validate_burgers_error.
integer, parameter burgers_eq_mod::icase_burgers1d_wavepropagation
Referenced by compute_burgers_rhs, initialize_burgers_flow.
real(wp) burgers_eq_mod::alpha
Referenced by compute_burgers_rhs, initialize_burgers_flow, validate_burgers_error.
real(wp) burgers_eq_mod::beta
Referenced by compute_burgers_rhs, initialize_burgers_flow, validate_burgers_error.
real(wp) burgers_eq_mod::nu
Referenced by compute_burgers_rhs, initialize_burgers_flow.
integer burgers_eq_mod::icase
Referenced by compute_burgers_rhs, initialize_burgers_flow, validate_burgers_error.
integer burgers_eq_mod::idir
Referenced by compute_burgers_rhs, initialize_burgers_flow, plot_burgers_profile, validate_burgers_error.
subroutine, public burgers_eq_mod::initialize_burgers_flow(dm, ux, uy, uz, p)
References alpha, beta, parameters_constant_mod::half, parameters_constant_mod::ibc_dirichlet, parameters_constant_mod::ibc_periodic, icase, icase_burgers1d, icase_burgers1d_inviscid, icase_burgers1d_viscous, icase_burgers1d_wavepropagation, idir, nu, parameters_constant_mod::one, parameters_constant_mod::pi, precision_mod::wp, parameters_constant_mod::zero.
Referenced by flow_thermo_initialiasation::initialize_flow_fields.
subroutine, private burgers_eq_mod::compute_burgers_rhs(fl, dm, isub)
References alpha, boundary_conditions_mod::apply_bc_velocity, beta, operations::get_x_1st_derivative_c2p_3d, operations::get_x_1st_derivative_p2c_3d, operations::get_x_midp_p2c_3d, operations::get_y_1st_derivative_c2p_3d, operations::get_y_2nd_derivative_p2p_3d, operations::get_y_midp_p2c_3d, parameters_constant_mod::half, icase, icase_burgers1d_inviscid, icase_burgers1d_viscous, icase_burgers1d_wavepropagation, idir, nu, parameters_constant_mod::one, parameters_constant_mod::zero.
Referenced by solve_burgers_eq_iteration.
subroutine, private burgers_eq_mod::validate_burgers_error(fl, dm)
References alpha, beta, icase, icase_burgers1d_inviscid, icase_burgers1d_viscous, idir, mpi_mod::ierror, precision_mod::mpi_real_wp, parameters_constant_mod::one, parameters_constant_mod::pi, parameters_constant_mod::two, parameters_constant_mod::twopi, precision_mod::wp, parameters_constant_mod::zero.
Referenced by solve_burgers_eq_iteration.
subroutine, public burgers_eq_mod::plot_burgers_profile(fl, dm, iter)
References idir, typeconvert_mod::int2str, parameters_constant_mod::one, precision_mod::wp, parameters_constant_mod::zero.
Referenced by solve_burgers_eq_iteration.
subroutine, public burgers_eq_mod::solve_burgers_eq_iteration
References code_performance_mod::call_cpu_time, compute_burgers_rhs, code_performance_mod::cpu_time_code_end, code_performance_mod::cpu_time_iter_start, vars_df_mod::domain, mpi_mod::finalise_mpi, vars_df_mod::flow, mpi_mod::nxdomain, plot_burgers_profile, vars_df_mod::thermo, solver_tools_mod::update_prgr, solver_tools_mod::update_re, validate_burgers_error.
Referenced by test_algorithms.