decomp_extended_mod
subroutine, public decomp_extended_mod::ypencil_index_lgl2ggl(vin, vou, dtmp)
References parameters_constant_mod::zero.
Referenced by continuity_eq_mod::get_divergence_vel_x2z.
subroutine, public decomp_extended_mod::zpencil_index_llg2ggg(vin, vou, dtmp)
References parameters_constant_mod::zero.
Referenced by continuity_eq_mod::get_divergence_vel_x2z, eq_momentum_mod::solve_poisson, eq_momentum_mod::solve_poisson_x2z.
subroutine, public decomp_extended_mod::zpencil_index_ggg2llg(vin, vou, dtmp)
References parameters_constant_mod::zero.
Referenced by eq_momentum_mod::solve_poisson, eq_momentum_mod::solve_poisson_x2z.