eq_energy_mod
subroutine, private eq_energy_mod::calculate_energy_fractional_step(rhs0, rhs1, dm, isub)
Referenced by compute_energy_rhs.
subroutine, private eq_energy_mod::compute_energy_rhs(fl, tm, dm, isub)
References calculate_energy_fractional_step, operations::get_x_1st_derivative_c2p_3d, operations::get_x_1st_derivative_p2c_3d, operations::get_x_midp_c2p_3d, operations::get_y_1st_derivative_c2p_3d, operations::get_y_1st_derivative_p2c_3d, operations::get_y_midp_c2p_3d, operations::get_z_1st_derivative_c2p_3d, operations::get_z_1st_derivative_p2c_3d, operations::get_z_midp_c2p_3d.
Referenced by solve_energy_eq.
subroutine, public eq_energy_mod::solve_energy_eq(fl, tm, dm, isub)
References compute_energy_rhs, thermo_info_mod::update_thermal_properties.
Referenced by solve_eqs_iteration.
subroutine, public eq_energy_mod::calculate_massflux_from_velocity(fl, dm)
Calculate the conservative variables from primary variable. This subroutine is called to update $\rho u_i$ from $u_i$.
Scope: mpi called-freq xdomain module all needed specified pubic dm domain fm flow
References operations::get_x_midp_c2p_1d, operations::get_y_midp_c2p_1d, operations::get_z_midp_c2p_1d.
Referenced by flow_thermo_initialiasation::initialize_thermo_fields, io_restart_mod::restore_thermo_variables_from_restart.