statistics_mod
character(13), parameter statistics_mod::io_name
integer, dimension(:, :), allocatable statistics_mod::ncl_stat
Referenced by init_statistics_flow, init_statistics_thermo.
subroutine, public statistics_mod::init_statistics_flow(fl, dm)
References parameters_constant_mod::init_restart, ncl_stat, read_statistics_array, parameters_constant_mod::zero.
Referenced by domain_decomposition_mod::buildup_mpi_domain_decomposition.
subroutine, public statistics_mod::init_statistics_thermo(tm, dm)
References parameters_constant_mod::init_restart, ncl_stat, read_statistics_array, parameters_constant_mod::zero.
Referenced by domain_decomposition_mod::buildup_mpi_domain_decomposition.
subroutine, public statistics_mod::update_statistics_flow(fl, dm)
References operations::get_x_midp_p2c_3d, operations::get_y_midp_p2c_3d, operations::get_z_midp_p2c_3d, parameters_constant_mod::one.
Referenced by solve_eqs_iteration.
subroutine, public statistics_mod::write_statistics_flow(fl, dm)
References write_statistics_array.
Referenced by solve_eqs_iteration.
subroutine, public statistics_mod::update_statistics_thermo(tm, dm)
References parameters_constant_mod::one.
Referenced by solve_eqs_iteration.
subroutine, public statistics_mod::write_statistics_thermo(tm, dm)
References write_statistics_array.
Referenced by solve_eqs_iteration.
subroutine, private statistics_mod::write_statistics_array(var, keyword, idm, iter, dtmp)
References files_io_mod::dir_data, io_tools_mod::generate_pathfile_name, io_tools_mod::x_pencil.
Referenced by write_statistics_flow, write_statistics_thermo.
subroutine, private statistics_mod::read_statistics_array(var, keyword, idm, iter, dtmp)
References files_io_mod::dir_data, io_tools_mod::generate_file_name.
Referenced by init_statistics_flow, init_statistics_thermo.