boundary_conditions_mod
subroutine, public boundary_conditions_mod::apply_bc_velocity(dm, ux, uy, uz)
Apply b.c. conditions.
Scope: mpi called-freq xdomain module all once specified public d domain f flow
References parameters_constant_mod::ibc_dirichlet.
Referenced by burgers_eq_mod::compute_burgers_rhs, flow_thermo_initialiasation::generate_random_field, flow_thermo_initialiasation::initialize_flow_from_given_values, flow_thermo_initialiasation::initialize_poiseuille_flow, io_restart_mod::restore_flow_variables_from_restart, eq_momentum_mod::solve_momentum_eq.
subroutine, public boundary_conditions_mod::apply_convective_outlet