tridiagonal_matrix_algorithm
subroutine, public tridiagonal_matrix_algorithm::preprocess_tdma_coeffs(a, b, c, d, n)
References parameters_constant_mod::one.
Referenced by operations::buildup_tdma_lhs_array, test_tdma_cyclic, test_tdma_noncyclic.
subroutine, private tridiagonal_matrix_algorithm::solve_tdma_basic(x, a, b, c, d, n)
Referenced by solve_tdma, solve_tdma_cyclic.
subroutine, private tridiagonal_matrix_algorithm::solve_tdma_cyclic(x, a, b, c, d, n)
References solve_tdma_basic.
Referenced by solve_tdma.
subroutine, public tridiagonal_matrix_algorithm::solve_tdma(peri, x, a, b, c, d, n)
References solve_tdma_basic, solve_tdma_cyclic.
Referenced by operations::get_x_1st_derivative_c2c_1d, operations::get_x_1st_derivative_c2p_1d, operations::get_x_1st_derivative_p2c_1d, operations::get_x_1st_derivative_p2p_1d, operations::get_x_2nd_derivative_c2c_1d, operations::get_x_2nd_derivative_p2p_1d, operations::get_x_midp_c2p_1d, operations::get_x_midp_p2c_1d, operations::get_y_1st_derivative_c2c_1d, operations::get_y_1st_derivative_c2p_1d, operations::get_y_1st_derivative_p2c_1d, operations::get_y_1st_derivative_p2p_1d, operations::get_y_2nd_derivative_c2c_1d, operations::get_y_2nd_derivative_p2p_1d, operations::get_y_midp_c2p_1d, operations::get_y_midp_p2c_1d, operations::get_z_1st_derivative_c2c_1d, operations::get_z_1st_derivative_c2p_1d, operations::get_z_1st_derivative_p2c_1d, operations::get_z_1st_derivative_p2p_1d, operations::get_z_2nd_derivative_c2c_1d, operations::get_z_2nd_derivative_p2p_1d, operations::get_z_midp_c2p_1d, operations::get_z_midp_p2c_1d, test_tdma_cyclic, test_tdma_noncyclic.
subroutine, public tridiagonal_matrix_algorithm::test_tdma_noncyclic
References preprocess_tdma_coeffs, solve_tdma.
Referenced by test_algorithms.
subroutine, public tridiagonal_matrix_algorithm::test_tdma_cyclic
References preprocess_tdma_coeffs, solve_tdma.
Referenced by test_algorithms.