poisson_interface.f90
real(mytype) function rl(complexnumber)
References rl.
Referenced by inversion5_v1, inversion5_v2, decomp_2d_poisson::matrice_refinement, decomp_2d_poisson::poisson_000, decomp_2d_poisson::poisson_010, decomp_2d_poisson::poisson_100, decomp_2d_poisson::poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, rl, decomp_2d_poisson::subroutine.
real(mytype) function iy(complexnumber)
References iy.
Referenced by inversion5_v1, inversion5_v2, iy, decomp_2d_poisson::matrice_refinement, decomp_2d_poisson::poisson_000, decomp_2d_poisson::poisson_010, decomp_2d_poisson::poisson_100, decomp_2d_poisson::poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, decomp_2d_poisson::subroutine, io_monitor_mod::write_monitor_flow, io_monitor_mod::write_monitor_thermo.
complex(mytype) function cx(realpart, imaginarypart)
References cx.
Referenced by cx, inversion5_v1, inversion5_v2, decomp_2d_poisson::matrice_refinement, decomp_2d_poisson::poisson_000, decomp_2d_poisson::poisson_010, decomp_2d_poisson::poisson_100, decomp_2d_poisson::poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx, decomp_2d_poisson::subroutine, decomp_2d_poisson::waves.
subroutine inversion5_v1(aaa_in, eee, spi)
References cx, iy, poisson_interface_mod::ny, rl.
Referenced by decomp_2d_poisson::poisson_010, decomp_2d_poisson::poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.
subroutine inversion5_v2(aaa, eee, spi)
References cx, iy, poisson_interface_mod::nym, rl.
Referenced by decomp_2d_poisson::poisson_010, decomp_2d_poisson::poisson_11x, decomp_2d_poisson::poisson_xxx::poisson_xxx.