tools_general.f90
subroutine print_error_msg(msg)
Referenced by geometry_mod::buildup_grid_mapping_1d, code_performance_mod::call_cpu_time, thermo_info_mod::ftp_get_thermal_properties_dimensional_from_t, thermo_info_mod::ftp_refresh_thermal_properties_from_dh, operations::get_x_1st_derivative_c2p_1d, operations::get_x_1st_derivative_c2p_3d, operations::get_x_1st_derivative_p2p_1d, operations::get_x_1st_derivative_p2p_3d, operations::get_x_midp_c2p_1d, operations::get_x_midp_c2p_3d, operations::get_y_1st_derivative_c2p_1d, operations::get_y_1st_derivative_c2p_3d, operations::get_y_1st_derivative_p2p_1d, operations::get_y_1st_derivative_p2p_3d, operations::get_y_midp_c2p_1d, operations::get_y_midp_c2p_3d, operations::get_z_1st_derivative_c2p_1d, operations::get_z_1st_derivative_c2p_3d, operations::get_z_1st_derivative_p2p_1d, operations::get_z_1st_derivative_p2p_3d, operations::get_z_midp_c2p_1d, operations::get_z_midp_c2p_3d, operations::prepare_tdma_1deri_c2c_rhs_array, operations::prepare_tdma_1deri_c2p_rhs_array, operations::prepare_tdma_1deri_p2p_rhs_array, operations::prepare_tdma_2deri_c2c_rhs_array, operations::prepare_tdma_interp_c2p_rhs_array, input_general_mod::read_input_parameters, eq_momentum_mod::solve_momentum_eq, io_visulisation_mod::write_field, io_visulisation_mod::write_snapshot_any3darray.
subroutine print_warning_msg(msg)
Referenced by solver_tools_mod::check_cfl_diffusion, thermo_info_mod::ftp_refresh_thermal_properties_from_dh, input_general_mod::read_input_parameters.
subroutine print_debug_start_msg(msg)
Referenced by flow_thermo_initialiasation::allocate_flow_variables, flow_thermo_initialiasation::allocate_thermo_variables, poisson_interface_mod::build_up_poisson_interface, geometry_mod::buildup_geometry_mesh_info, thermo_info_mod::buildup_property_relations_from_function, thermo_info_mod::buildup_property_relations_from_table, code_performance_mod::call_cpu_time, eq_momentum_mod::compute_momentum_rhs, flow_thermo_initialiasation::generate_random_field, solver_tools_mod::get_volumetric_average_3d, initialize_chapsim, flow_thermo_initialiasation::initialize_flow_fields, flow_thermo_initialiasation::initialize_thermo_fields, thermo_info_mod::initialize_thermo_parameters, operations::prepare_compact_coefficients, input_general_mod::read_input_parameters, io_restart_mod::read_instantanous_flow_raw_data, io_restart_mod::read_instantanous_thermo_raw_data, solve_eqs_iteration, eq_momentum_mod::solve_poisson, io_restart_mod::write_instantanous_flow_raw_data, io_restart_mod::write_instantanous_thermo_raw_data.
subroutine print_debug_mid_msg(msg)
Referenced by thermo_info_mod::buildup_property_relations_from_function, thermo_info_mod::buildup_property_relations_from_table, code_performance_mod::call_cpu_time, eq_momentum_mod::correct_massflux, flow_thermo_initialiasation::generate_poiseuille_flow_profile, flow_thermo_initialiasation::initialize_flow_from_given_values, flow_thermo_initialiasation::initialize_poiseuille_flow, thermo_info_mod::initialize_thermal_properties, flow_thermo_initialiasation::initialize_vortexgreen_2dflow, flow_thermo_initialiasation::initialize_vortexgreen_3dflow, io_restart_mod::restore_flow_variables_from_restart, eq_momentum_mod::solve_momentum_eq, eq_momentum_mod::solve_poisson, flow_thermo_initialiasation::validate_tgv2d_error.
subroutine print_debug_end_msg
Referenced by flow_thermo_initialiasation::allocate_flow_variables, flow_thermo_initialiasation::allocate_thermo_variables, poisson_interface_mod::build_up_poisson_interface, geometry_mod::buildup_geometry_mesh_info, flow_thermo_initialiasation::generate_poiseuille_flow_profile, flow_thermo_initialiasation::generate_random_field, initialize_chapsim, flow_thermo_initialiasation::initialize_flow_from_given_values, flow_thermo_initialiasation::initialize_poiseuille_flow, thermo_info_mod::initialize_thermal_properties, thermo_info_mod::initialize_thermo_parameters, flow_thermo_initialiasation::initialize_vortexgreen_2dflow, flow_thermo_initialiasation::initialize_vortexgreen_3dflow, operations::prepare_compact_coefficients, input_general_mod::read_input_parameters, io_restart_mod::read_instantanous_flow_raw_data, io_restart_mod::read_instantanous_thermo_raw_data, flow_thermo_initialiasation::validate_tgv2d_error, io_restart_mod::write_instantanous_flow_raw_data, io_restart_mod::write_instantanous_thermo_raw_data.
subroutine print_3d_array(var, nx, ny, nz, str)