.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src Directory Reference" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalgorithms\&.f90\fP"
.br
.ti -1c
.RI "file \fBboundary_conditions\&.f90\fP"
.br
.ti -1c
.RI "file \fBchapsim\&.f90\fP"
.br
.RI "the main program\&. "
.ti -1c
.RI "file \fBdomain_decomposition\&.f90\fP"
.br
.ti -1c
.RI "file \fBeq_continuity\&.f90\fP"
.br
.ti -1c
.RI "file \fBeq_energy\&.f90\fP"
.br
.ti -1c
.RI "file \fBeq_momentum\&.f90\fP"
.br
.ti -1c
.RI "file \fBeq_scalar_transport\&.f90\fP"
.br
.ti -1c
.RI "file \fBflow_initialization\&.f90\fP"
.br
.ti -1c
.RI "file \fBgeometry\&.f90\fP"
.br
.RI "Building up the geometry and mesh information\&. "
.ti -1c
.RI "file \fBinput_general\&.f90\fP"
.br
.RI "Reading the input parameters from the given file\&. "
.ti -1c
.RI "file \fBinput_thermo\&.f90\fP"
.br
.RI "Reading the input parameters from the given file and building up the relationships between properties\&. "
.ti -1c
.RI "file \fBio_monitor\&.f90\fP"
.br
.ti -1c
.RI "file \fBio_restart\&.f90\fP"
.br
.ti -1c
.RI "file \fBio_tools\&.f90\fP"
.br
.ti -1c
.RI "file \fBio_visulisation\&.f90\fP"
.br
.ti -1c
.RI "file \fBmodules\&.f90\fP"
.br
.ti -1c
.RI "file \fBmpi_mod\&.f90\fP"
.br
.ti -1c
.RI "file \fBoperations\&.f90\fP"
.br
.RI "A general operation of derivative and interpolation in 1D\&. "
.ti -1c
.RI "file \fBpoisson_1stderivcomp\&.f90\fP"
.br
.ti -1c
.RI "file \fBpoisson_1stderivcomp_reform\&.f90\fP"
.br
.ti -1c
.RI "file \fBpoisson_2ndderivcomp\&.f90\fP"
.br
.ti -1c
.RI "file \fBpoisson_interface\&.f90\fP"
.br
.ti -1c
.RI "file \fBstatistics\&.f90\fP"
.br
.ti -1c
.RI "file \fBtest_algrithms\&.f90\fP"
.br
.ti -1c
.RI "file \fBtools_general\&.f90\fP"
.br
.ti -1c
.RI "file \fBtools_solver\&.f90\fP"
.br
.in -1c
