.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/boundary_conditions.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/boundary_conditions.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBboundary_conditions_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBboundary_conditions_mod::apply_bc_velocity\fP (dm, ux, uy, uz)"
.br
.RI "Apply b\&.c\&. conditions\&. "
.ti -1c
.RI "subroutine, public \fBboundary_conditions_mod::apply_convective_outlet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
