.TH "boundary_conditions_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boundary_conditions_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBapply_bc_velocity\fP (dm, ux, uy, uz)"
.br
.RI "Apply b\&.c\&. conditions\&. "
.ti -1c
.RI "subroutine, public \fBapply_convective_outlet\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public boundary_conditions_mod::apply_bc_velocity (type(\fBt_domain\fP), intent(in) dm, real(wp), dimension(dm%dpcc%xsz(1), dm%dpcc%xsz(2), dm%dpcc%xsz(3)), intent(inout) ux, real(wp), dimension(dm%dcpc%xsz(1), dm%dcpc%xsz(2), dm%dcpc%xsz(3)), intent(inout) uy, real(wp), dimension(dm%dccp%xsz(1), dm%dccp%xsz(2), dm%dccp%xsz(3)), intent(inout) uz)"

.PP
Apply b\&.c\&. conditions\&. Scope: mpi called-freq xdomain module all once specified public 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain 
.br
\fIf\fP flow 
.RE
.PP

.SS "subroutine, public boundary_conditions_mod::apply_convective_outlet"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
