.TH "burgers_eq_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
burgers_eq_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinitialize_burgers_flow\fP (dm, ux, uy, uz, p)"
.br
.ti -1c
.RI "subroutine, private \fBcompute_burgers_rhs\fP (fl, dm, isub)"
.br
.ti -1c
.RI "subroutine, private \fBvalidate_burgers_error\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBplot_burgers_profile\fP (fl, dm, iter)"
.br
.ti -1c
.RI "subroutine, public \fBsolve_burgers_eq_iteration\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBicase_burgers1d\fP = 11"
.br
.ti -1c
.RI "integer, parameter \fBicase_burgers1d_viscous\fP = 12"
.br
.ti -1c
.RI "integer, parameter \fBicase_burgers1d_inviscid\fP = 13"
.br
.ti -1c
.RI "integer, parameter \fBicase_burgers1d_wavepropagation\fP = 14"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBalpha\fP = ONE"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBbeta\fP = ZERO"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBnu\fP"
.br
.ti -1c
.RI "integer \fBicase\fP = 11"
.br
.ti -1c
.RI "integer \fBidir\fP = 1"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, private burgers_eq_mod::compute_burgers_rhs (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm, integer(4), intent(in) isub)\fC [private]\fP"

.SS "subroutine, public burgers_eq_mod::initialize_burgers_flow (type(\fBt_domain\fP), intent(inout) dm, real(\fBwp\fP), dimension(:, :, :), intent(inout) ux, real(\fBwp\fP), dimension(:, :, :), intent(inout) uy, real(\fBwp\fP), dimension(:, :, :), intent(inout) uz, real(\fBwp\fP), dimension (:, :, :), intent(inout) p)"

.SS "subroutine, public burgers_eq_mod::plot_burgers_profile (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) iter)"

.SS "subroutine, public burgers_eq_mod::solve_burgers_eq_iteration"

.SS "subroutine, private burgers_eq_mod::validate_burgers_error (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm)\fC [private]\fP"

.SH "Variable Documentation"
.PP 
.SS "real(\fBwp\fP) burgers_eq_mod::alpha = ONE"

.SS "real(\fBwp\fP) burgers_eq_mod::beta = ZERO"

.SS "integer burgers_eq_mod::icase = 11"

.SS "integer, parameter burgers_eq_mod::icase_burgers1d = 11"

.SS "integer, parameter burgers_eq_mod::icase_burgers1d_inviscid = 13"

.SS "integer, parameter burgers_eq_mod::icase_burgers1d_viscous = 12"

.SS "integer, parameter burgers_eq_mod::icase_burgers1d_wavepropagation = 14"

.SS "integer burgers_eq_mod::idir = 1"

.SS "real(\fBwp\fP) burgers_eq_mod::nu"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
