.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/chapsim.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/chapsim.f90 \- the main program\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "program \fBchapsim\fP"
.br
.ti -1c
.RI "subroutine \fBinitialize_chapsim\fP"
.br
.RI "Initialisation and preprocessing of geometry, mesh and tools This subroutine is called at beginning of the main program\&. "
.ti -1c
.RI "subroutine \fBsolve_eqs_iteration\fP"
.br
.RI "solve the governing equations in iteration "
.ti -1c
.RI "subroutine \fBfinalise_chapsim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
the main program\&. 


.SS "CHAPSim version 2\&.0\&.0"
This file is part of CHAPSim, a general-purpose CFD tool\&.
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA\&. 
.PP
\fBAuthor\fP
.RS 4
Wei Wang wei.wang@stfc.ac.uk 
.RE
.PP
\fBDate\fP
.RS 4
.RE
.PP

.SH "Function/Subroutine Documentation"
.PP 
.SS "program chapsim"

.SS "subroutine finalise_chapsim"

.SS "subroutine initialize_chapsim"

.PP
Initialisation and preprocessing of geometry, mesh and tools This subroutine is called at beginning of the main program\&. 
.SS "subroutine solve_eqs_iteration"

.PP
solve the governing equations in iteration This subroutine is the main solver\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.br
\fInone\fP NA 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
