.TH "code_performance_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code_performance_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBconvert_sec_to_hms\fP (s, hrs, mins, secs)"
.br
.ti -1c
.RI "subroutine, public \fBcall_cpu_time\fP (itype, iterfrom, niter, iter)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBcpu_time_code_start\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBcpu_time_step_start\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBcpu_time_iter_start\fP = 3"
.br
.ti -1c
.RI "integer, parameter \fBcpu_time_iter_end\fP = 4"
.br
.ti -1c
.RI "integer, parameter \fBcpu_time_step_end\fP = 5"
.br
.ti -1c
.RI "integer, parameter \fBcpu_time_code_end\fP = 6"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_code_start\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_step_start\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_iter_start\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_iter_end\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_step_end\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), save \fBt_code_end\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public code_performance_mod::call_cpu_time (integer, intent(in) itype, integer, intent(in) iterfrom, integer, intent(in) niter, integer, intent(in), optional iter)"

.SS "subroutine, private code_performance_mod::convert_sec_to_hms (real(\fBwp\fP), intent(in) s, integer, intent(out) hrs, integer, intent(out) mins, real(\fBwp\fP), intent(out) secs)\fC [private]\fP"

.SH "Variable Documentation"
.PP 
.SS "integer, parameter code_performance_mod::cpu_time_code_end = 6"

.SS "integer, parameter code_performance_mod::cpu_time_code_start = 1"

.SS "integer, parameter code_performance_mod::cpu_time_iter_end = 4"

.SS "integer, parameter code_performance_mod::cpu_time_iter_start = 3"

.SS "integer, parameter code_performance_mod::cpu_time_step_end = 5"

.SS "integer, parameter code_performance_mod::cpu_time_step_start = 2"

.SS "real(\fBwp\fP), save code_performance_mod::t_code_end"

.SS "real(\fBwp\fP), save code_performance_mod::t_code_start"

.SS "real(\fBwp\fP), save code_performance_mod::t_iter_end"

.SS "real(\fBwp\fP), save code_performance_mod::t_iter_start"

.SS "real(\fBwp\fP), save code_performance_mod::t_step_end"

.SS "real(\fBwp\fP), save code_performance_mod::t_step_start"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
