.TH "decomp_2d_poisson" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decomp_2d_poisson
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBpoisson_xxx\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "\fBsubroutine\fP, public \fBdecomp_2d_poisson_init\fP ()"
.br
.ti -1c
.RI "\fBsubroutine\fP, public \fBdecomp_2d_poisson_finalize\fP"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_000\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_100\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_010\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_11x\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBabxyz\fP (\fBax\fP, \fBay\fP, \fBaz\fP, \fBbx\fP, \fBby\fP, \fBbz\fP, \fBnx\fP, \fBny\fP, \fBnz\fP, \fBbcx\fP, \fBbcy\fP, \fBbcz\fP)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBwaves\fP ()"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBmatrice_refinement\fP ()"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBavg3d\fP (var, avg)"
.br
.ti -1c
.RI "\fBsubroutine\fP, private \fBcomplex_half_unit\fP"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBfft3d_sp_shift_half_x0\fP (\fBcw1\fP, isign)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBfft3d_sp_shift_half_x1\fP (\fBcw1\fP, isign)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBfft3d_sp_shift_half_y0\fP (\fBcw1\fP, isign)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBfft3d_sp_shift_half_y1\fP (\fBcw1\fP)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBfft3d_sp_shift_half_z0\fP (\fBcw1\fP, isign)"
.br
.ti -1c
.RI "subroutine \fBsubroutine\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(mytype), parameter \fBepsilon\fP = 1\&.e\-20_mytype"
.br
.ti -1c
.RI "integer, save \fBbcx\fP"
.br
.ti -1c
.RI "integer, save \fBbcy\fP"
.br
.ti -1c
.RI "integer, save \fBbcz\fP"
.br
.ti -1c
.RI "type(decomp_info), save \fBph\fP"
.br
.ti -1c
.RI "type(decomp_info), save \fBsp\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBaz\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBbz\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBay\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBby\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBax\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBbx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable, save \fBkxyz\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBa\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBa2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBa3\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBrw1\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBrw1b\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBrw2\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBrw2b\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBrw3\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw1\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw1b\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw22\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw2b\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBcw2c\fP"
.br
.ti -1c
.RI "logical, save \fBfft_initialised\fP = \&.false\&."
.br
.ti -1c
.RI "procedure(\fBpoisson_xxx\fP), pointer, public \fBpoisson\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBcplx_circle_unit_halfx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBcplx_circle_unit_halfy\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBcplx_circle_unit_halfz\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBwx\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBwy\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBwz\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "\fBsubroutine\fP decomp_2d_poisson::abxyz (real(mytype), dimension(:), intent(out) ax, real(mytype), dimension(:), intent(out) ay, real(mytype), dimension(:), intent(out) az, real(mytype), dimension(:), intent(out) bx, real(mytype), dimension(:), intent(out) by, real(mytype), dimension(:), intent(out) bz, integer, intent(in) nx, integer, intent(in) ny, integer, intent(in) nz, integer, intent(in) bcx, integer, intent(in) bcy, integer, intent(in) bcz)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::avg3d (real(mytype), dimension(xsize(1),xsize(2),xsize(3)), intent(in) var, real(mytype), intent(out) avg)\fC [private]\fP"

.SS "\fBsubroutine\fP, private decomp_2d_poisson::complex_half_unit\fC [private]\fP"

.SS "\fBsubroutine\fP public decomp_2d_poisson::decomp_2d_poisson_finalize"

.SS "\fBsubroutine\fP public decomp_2d_poisson::decomp_2d_poisson_init"

.SS "\fBsubroutine\fP decomp_2d_poisson::fft3d_sp_shift_half_x0 (complex(mytype), dimension(\fBsp\fP%xst(1) : \fBsp\fP%xen(1),                                 \fBsp\fP%xst(2) : \fBsp\fP%xen(2),                                 \fBsp\fP%xst(3) : \fBsp\fP%xen(3)), intent(inout) cw1, integer, intent(in) isign)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::fft3d_sp_shift_half_x1 (complex(mytype), dimension(\fBsp\fP%xst(1) : \fBsp\fP%xen(1),                                 \fBsp\fP%xst(2) : \fBsp\fP%xen(2),                                 \fBsp\fP%xst(3) : \fBsp\fP%xen(3)), intent(inout) cw1,  isign)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::fft3d_sp_shift_half_y0 (complex(mytype), dimension( \fBsp\fP%xst(1) : \fBsp\fP%xen(1),                                 \fBsp\fP%xst(2) : \fBsp\fP%xen(2),                                 \fBsp\fP%xst(3) : \fBsp\fP%xen(3)), intent(in) cw1, integer, intent(in) isign)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::fft3d_sp_shift_half_y1 (complex(mytype), dimension( \fBsp\fP%xst(1) : \fBsp\fP%xen(1),                                 \fBsp\fP%xst(2) : \fBsp\fP%xen(2),                                 \fBsp\fP%xst(3) : \fBsp\fP%xen(3)), intent(in) cw1)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::fft3d_sp_shift_half_z0 (complex(mytype), dimension( \fBsp\fP%xst(1) : \fBsp\fP%xen(1),                                 \fBsp\fP%xst(2) : \fBsp\fP%xen(2),                                 \fBsp\fP%xst(3) : \fBsp\fP%xen(3)), intent(in) cw1, integer, intent(in) isign)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::matrice_refinement\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_000 (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_010 (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_100 (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_11x (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [private]\fP"

.SS "subroutine decomp_2d_poisson::subroutine ( waves)\fC [private]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::waves\fC [private]\fP"

.SH "Variable Documentation"
.PP 
.SS "complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a2\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:,:), allocatable, save decomp_2d_poisson::a3\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::ax\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::ay\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::az\fC [private]\fP"

.SS "integer save decomp_2d_poisson::bcx\fC [private]\fP"

.SS "integer save decomp_2d_poisson::bcy\fC [private]\fP"

.SS "integer save decomp_2d_poisson::bcz\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::bx\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::by\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::bz\fC [private]\fP"

.SS "complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfx\fC [private]\fP"

.SS "complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfy\fC [private]\fP"

.SS "complex(mytype), dimension(:), allocatable, save decomp_2d_poisson::cplx_circle_unit_halfz\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw1\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw1b\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw22\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2b\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::cw2c\fC [private]\fP"

.SS "real(mytype), parameter decomp_2d_poisson::epsilon = 1\&.e\-20_mytype\fC [private]\fP"

.SS "logical save decomp_2d_poisson::fft_initialised = \&.false\&.\fC [private]\fP"

.SS "complex(mytype), dimension(:,:,:), allocatable, save decomp_2d_poisson::kxyz\fC [private]\fP"

.SS "type(decomp_info), save decomp_2d_poisson::ph\fC [private]\fP"

.SS "procedure (\fBpoisson_xxx\fP), pointer, public decomp_2d_poisson::poisson"

.SS "real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw1\fC [private]\fP"

.SS "real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw1b\fC [private]\fP"

.SS "real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw2\fC [private]\fP"

.SS "real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw2b\fC [private]\fP"

.SS "real(mytype), dimension(:,:,:), allocatable decomp_2d_poisson::rw3\fC [private]\fP"

.SS "type(decomp_info), save decomp_2d_poisson::sp\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wx\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wy\fC [private]\fP"

.SS "real(mytype), dimension(:), allocatable, save decomp_2d_poisson::wz\fC [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
