.TH "decomp_extended_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decomp_extended_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBypencil_index_lgl2ggl\fP (vin, vou, dtmp)"
.br
.ti -1c
.RI "subroutine, public \fBzpencil_index_llg2ggg\fP (vin, vou, dtmp)"
.br
.ti -1c
.RI "subroutine, public \fBzpencil_index_ggg2llg\fP (vin, vou, dtmp)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public decomp_extended_mod::ypencil_index_lgl2ggl (real(\fBwp\fP), dimension(dtmp%ysz(1),               dtmp%ysz(2), dtmp%ysz(3)), intent(in) vin, real(\fBwp\fP), dimension(dtmp%yst(1) : dtmp%yen(2), dtmp%ysz(2), dtmp%zsz(3)), intent(out) vou, type(decomp_info), intent(in) dtmp)"

.SS "subroutine, public decomp_extended_mod::zpencil_index_ggg2llg (real(\fBwp\fP), dimension(dtmp%zst(1) : dtmp%zen(1), dtmp%zst(2) : dtmp%zen(2), dtmp%zsz(3)), intent(in) vin, real(\fBwp\fP), dimension(dtmp%zsz(1),               dtmp%zsz(2),               dtmp%zsz(3)), intent(out) vou, type(decomp_info), intent(in) dtmp)"

.SS "subroutine, public decomp_extended_mod::zpencil_index_llg2ggg (real(\fBwp\fP), dimension(dtmp%zsz(1),               dtmp%zsz(2),               dtmp%zsz(3)), intent(in) vin, real(\fBwp\fP), dimension(dtmp%zst(1) : dtmp%zen(1), dtmp%zst(2) : dtmp%zen(2), dtmp%zsz(3)), intent(out) vou, type(decomp_info), intent(in) dtmp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
