.TH "decomp_2d_poisson::poisson_xxx" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
decomp_2d_poisson::poisson_xxx
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_xxx\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_xxx\fP (rhs)"
.br
.ti -1c
.RI "\fBsubroutine\fP \fBpoisson_xxx\fP (rhs)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_xxx::poisson_xxx (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [virtual]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_xxx::poisson_xxx (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [virtual]\fP"

.SS "\fBsubroutine\fP decomp_2d_poisson::poisson_xxx::poisson_xxx (real(mytype), dimension(:,:,:), intent(inout) rhs)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
