.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/domain_decomposition.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/domain_decomposition.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdomain_decomposition_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBdomain_decomposition_mod::initialize_domain_decomposition\fP (dm)"
.br
.RI "domain decompistion\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBdomain_decomposition_mod::buildup_mpi_domain_decomposition\fP"
.br
.RI "domain decompistion\&. 
.br
 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
