.TH "domain_decomposition_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
domain_decomposition_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBinitialize_domain_decomposition\fP (dm)"
.br
.RI "domain decompistion\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBbuildup_mpi_domain_decomposition\fP"
.br
.RI "domain decompistion\&. 
.br
 "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public domain_decomposition_mod::buildup_mpi_domain_decomposition"

.PP
domain decompistion\&. 
.br
 Scope: mpi called-freq xdomain module all once all public 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, private domain_decomposition_mod::initialize_domain_decomposition (type(\fBt_domain\fP), intent(inout) dm)\fC [private]\fP"

.PP
domain decompistion\&. 
.br
 Scope: mpi called-freq xdomain module all once specified priviate 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
