.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/eq_continuity.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/eq_continuity.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBcontinuity_eq_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBcontinuity_eq_mod::calculate_drhodt\fP (dm, ddens, ddensm1, ddensm2, drhodt)"
.br
.RI "To calculate d(\\rho)/dt in the continuity eq\&. "
.ti -1c
.RI "subroutine, public \fBcontinuity_eq_mod::get_divergence_vel\fP (ux, uy, uz, div, dm)"
.br
.RI "To calculate divergence of (rho * u) or divergence of (u) "
.ti -1c
.RI "subroutine, public \fBcontinuity_eq_mod::get_divergence_vel_x2z\fP (ux, uy, uz, div_zpencil_ggg, dm)"
.br
.RI "To calculate divergence of (rho * u) or divergence of (u) "
.ti -1c
.RI "subroutine, public \fBcontinuity_eq_mod::check_mass_conservation\fP (fl, dm)"
.br
.RI "To calculate divergence of (rho * u) or divergence of (u) "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
