.TH "eq_energy_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eq_energy_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBcalculate_energy_fractional_step\fP (rhs0, rhs1, dm, isub)"
.br
.ti -1c
.RI "subroutine, private \fBcompute_energy_rhs\fP (fl, tm, dm, isub)"
.br
.ti -1c
.RI "subroutine, public \fBsolve_energy_eq\fP (fl, tm, dm, isub)"
.br
.ti -1c
.RI "subroutine, public \fBcalculate_massflux_from_velocity\fP (fl, dm)"
.br
.RI "Calculate the conservative variables from primary variable\&. 
.br
 This subroutine is called to update $\\rho u_i$ from $u_i$\&. "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, private eq_energy_mod::calculate_energy_fractional_step (real(wp), dimension(dm%dccc%xsz(1), dm%dccc%xsz(2), dm%dccc%xsz(3)), intent(inout) rhs0, real(wp), dimension(dm%dccc%xsz(1), dm%dccc%xsz(2), dm%dccc%xsz(3)), intent(inout) rhs1, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)\fC [private]\fP"

.SS "subroutine, public eq_energy_mod::calculate_massflux_from_velocity (type(\fBt_flow\fP ), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm)"

.PP
Calculate the conservative variables from primary variable\&. 
.br
 This subroutine is called to update $\\rho u_i$ from $u_i$\&. Scope: mpi called-freq xdomain module all needed specified pubic 
.PP
\fBParameters\fP
.RS 4
\fIdm\fP domain 
.br
\fIfm\fP flow 
.RE
.PP

.SS "subroutine, private eq_energy_mod::compute_energy_rhs (type(\fBt_flow\fP), intent(in) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)\fC [private]\fP"

.SS "subroutine, public eq_energy_mod::solve_energy_eq (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
