.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/eq_momentum.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/eq_momentum.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBeq_momentum_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBeq_momentum_mod::calculate_momentum_fractional_step\fP (rhs0, rhs1, rhs1_pfc, dtmp, dm, isub)"
.br
.RI "To calcuate the convection and diffusion terms in rhs of momentum eq\&. "
.ti -1c
.RI "subroutine, private \fBeq_momentum_mod::compute_momentum_rhs\fP (fl, dm, isub)"
.br
.RI "To calcuate all rhs of momentum eq\&. "
.ti -1c
.RI "subroutine, private \fBeq_momentum_mod::correct_massflux\fP (ux, uy, uz, phi_ccc, dm, isub)"
.br
.ti -1c
.RI "subroutine, private \fBeq_momentum_mod::solve_poisson\fP (fl, dm, isub)"
.br
.ti -1c
.RI "subroutine, private \fBeq_momentum_mod::solve_poisson_x2z\fP (fl, dm, isub)"
.br
.ti -1c
.RI "subroutine, public \fBeq_momentum_mod::solve_momentum_eq\fP (fl, dm, isub)"
.br
.RI "To update the provisional u or rho u\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
