.TH "eq_scalar_transport_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eq_scalar_transport_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBcalculate_transport_fractional_step\fP (rhs0, rhs1, dm, isub)"
.br
.ti -1c
.RI "subroutine, private \fBcompute_transport_rhs\fP (fl, tm, dm, isub)"
.br
.ti -1c
.RI "subroutine, public \fBsolve_transport_eq\fP (fl, tm, dm, isub)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, private eq_scalar_transport_mod::calculate_transport_fractional_step (real(wp), dimension(dm%dccc%xsz(1), dm%dccc%xsz(2), dm%dccc%xsz(3)), intent(inout) rhs0, real(wp), dimension(dm%dccc%xsz(1), dm%dccc%xsz(2), dm%dccc%xsz(3)), intent(inout) rhs1, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)\fC [private]\fP"

.SS "subroutine, private eq_scalar_transport_mod::compute_transport_rhs (type(\fBt_flow\fP), intent(in) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)\fC [private]\fP"

.SS "subroutine, public eq_scalar_transport_mod::solve_transport_eq (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) isub)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
