.TH "files_io_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
files_io_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBcreate_directory\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(9) \fBdir_data\fP ='1_data'"
.br
.ti -1c
.RI "character(6) \fBdir_visu\fP ='2_visu'"
.br
.ti -1c
.RI "character(9) \fBdir_moni\fP ='3_monitor'"
.br
.ti -1c
.RI "character(9) \fBdir_chkp\fP ='4_check'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public files_io_mod::create_directory"

.SH "Variable Documentation"
.PP 
.SS "character(9) files_io_mod::dir_chkp ='4_check'"

.SS "character(9) files_io_mod::dir_data ='1_data'"

.SS "character(9) files_io_mod::dir_moni ='3_monitor'"

.SS "character(6) files_io_mod::dir_visu ='2_visu'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
