.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/geometry.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/geometry.f90 \- Building up the geometry and mesh information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBgeometry_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBgeometry_mod::buildup_grid_mapping_1d\fP (str, n, dm, y, mp)"
.br
.RI "Building up the mesh mapping relation between physical domain and mesh to a computational domain and mesh\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBgeometry_mod::buildup_geometry_mesh_info\fP (dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBgeometry_mod::ndm\fP = 0"
.br
.ti -1c
.RI "real(wp) \fBgeometry_mod::alpha\fP"
.br
.ti -1c
.RI "real(wp) \fBgeometry_mod::beta\fP"
.br
.ti -1c
.RI "real(wp) \fBgeometry_mod::gamma\fP"
.br
.ti -1c
.RI "real(wp) \fBgeometry_mod::delta\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Building up the geometry and mesh information\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
