.TH "geometry_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geometry_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBbuildup_grid_mapping_1d\fP (str, n, dm, y, mp)"
.br
.RI "Building up the mesh mapping relation between physical domain and mesh to a computational domain and mesh\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBbuildup_geometry_mesh_info\fP (dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBndm\fP = 0"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBalpha\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBbeta\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBgamma\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBdelta\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public geometry_mod::buildup_geometry_mesh_info (type(\fBt_domain\fP), intent(inout) dm)"

.SS "subroutine, private geometry_mod::buildup_grid_mapping_1d (character(len = *), intent(in) str, integer, intent(in) n, type(\fBt_domain\fP), intent(in) dm, real(\fBwp\fP), dimension(n), intent(out) y, real(\fBwp\fP), dimension(n, 3), intent(out) mp)\fC [private]\fP"

.PP
Building up the mesh mapping relation between physical domain and mesh to a computational domain and mesh\&. 
.br
 This subroutine is used locally for 1D only\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP string to indicate mapping of cell centre or nodes 
.br
\fIn\fP number of mapping points 
.br
\fIy\fP the physical coordinate array 
.br
\fImp\fP the mapping relations for 1st and 2nd deriviatives 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "real(\fBwp\fP) geometry_mod::alpha"

.SS "real(\fBwp\fP) geometry_mod::beta"

.SS "real(\fBwp\fP) geometry_mod::delta"

.SS "real(\fBwp\fP) geometry_mod::gamma"

.SS "integer, save geometry_mod::ndm = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
