.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/input_thermo.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/input_thermo.f90 \- Reading the input parameters from the given file and building up the relationships between properties\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBthermo_info_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_is_t_in_scope\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to check the temperature limitations\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_get_thermal_properties_dimensional_from_t\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known temperature\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_refresh_thermal_properties_from_t_undim\fP (this)"
.br
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_refresh_thermal_properties_from_h\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBthermo_info_mod::ftp_refresh_thermal_properties_from_dh\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy per unit mass\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_print\fP (this, unit, iotype, v_list, iostat, iomsg)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to print out the thermal properties at the given element\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftplist_sort_t_small2big\fP"
.br
.RI "Sort out the user given thermal property table based on the temperature from small to big\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftplist_check_monotonicity_dh_of_hort\fP"
.br
.RI "Check the monotonicity of the $\\rho h$ along $h$ and $T$\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::buildup_property_relations_from_table\fP"
.br
.RI "Building up the thermal property relations from the given table\&. This subroutine is called once after reading the table\&. [mpi] all ranks\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::ftp_convert_undim_to_dim\fP (ftp_undim, ftp_dim)"
.br
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::buildup_property_relations_from_function\fP"
.br
.RI "Building up the thermal property relations from defined relations\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::write_thermo_property\fP"
.br
.RI "Write out the rebuilt thermal property relations\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::initialize_thermo_parameters\fP (tm)"
.br
.RI "Identify table or equations for thermal properties based on input fluid material\&. "
.ti -1c
.RI "subroutine, private \fBthermo_info_mod::convert_thermo_bc_from_dim_to_undim\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBthermo_info_mod::initialize_thermal_properties\fP (fl, tm)"
.br
.RI "Initialise thermal variables if ithermo = 1\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBthermo_info_mod::buildup_thermo_mapping_relations\fP (tm, dm)"
.br
.RI "The main code for thermal property initialisation\&. Scope: mpi called-freq xdomain all once all\&. "
.ti -1c
.RI "subroutine, public \fBthermo_info_mod::update_thermal_properties\fP (fl, tm, dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBthermo_info_mod::n_func2table\fP = 1024"
.br
.ti -1c
.RI "logical \fBthermo_info_mod::is_ftplist_dim\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP), dimension(:), allocatable, save \fBthermo_info_mod::ftplist\fP"
.br
.ti -1c
.RI "type(\fBt_fluid_parameter\fP), save \fBthermo_info_mod::fluidparam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reading the input parameters from the given file and building up the relationships between properties\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
