.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/input_general.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/input_general.f90 \- Reading the input parameters from the given file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBinput_general_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinput_general_mod::read_input_parameters\fP"
.br
.RI "Reading the input parameters from the given file\&. 
.br
 Scope: mpi called-freq xdomain all once all\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBinput_general_mod::cpu_nfre\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reading the input parameters from the given file\&. 


.PP
\fBAuthor\fP
.RS 4
Wei Wang wei.wang@stfc.ac.uk 
.RE
.PP
\fBDate\fP
.RS 4
11-05-2022, checked\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
