.TH "input_general_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_general_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBread_input_parameters\fP"
.br
.RI "Reading the input parameters from the given file\&. 
.br
 Scope: mpi called-freq xdomain all once all\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBcpu_nfre\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public input_general_mod::read_input_parameters"

.PP
Reading the input parameters from the given file\&. 
.br
 Scope: mpi called-freq xdomain all once all\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.br
\fInone\fP NA 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "integer input_general_mod::cpu_nfre"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
