.TH "io_restart_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_restart_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBwrite_instantanous_flow_raw_data\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_instantanous_thermo_raw_data\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBread_instantanous_flow_raw_data\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBrestore_flow_variables_from_restart\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBread_instantanous_thermo_raw_data\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBrestore_thermo_variables_from_restart\fP (fl, tm, dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len=10), parameter \fBio_name\fP = 'restart\-io'"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public io_restart_mod::read_instantanous_flow_raw_data (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(inout) dm)"

.SS "subroutine, public io_restart_mod::read_instantanous_thermo_raw_data (type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(inout) dm)"

.SS "subroutine, public io_restart_mod::restore_flow_variables_from_restart (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_restart_mod::restore_thermo_variables_from_restart (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_restart_mod::write_instantanous_flow_raw_data (type(\fBt_flow\fP), intent(in) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_restart_mod::write_instantanous_thermo_raw_data (type(\fBt_thermo\fP), intent(in) tm, type(\fBt_domain\fP), intent(in) dm)"

.SH "Variable Documentation"
.PP 
.SS "character(len=10), parameter io_restart_mod::io_name = 'restart\-io'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
