.TH "io_tools_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_tools_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinitialize_decomp_io\fP (dm)"
.br
.ti -1c
.RI "subroutine, public \fBgenerate_pathfile_name\fP (flname, dmtag, keyword, path, extension, timetag)"
.br
.ti -1c
.RI "subroutine, public \fBgenerate_file_name\fP (flname, dmtag, keyword, extension, timetag)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBivisudim_3d\fP = 0"
.br
.ti -1c
.RI "integer, parameter \fBivisudim_2d_xa\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBivisudim_2d_ya\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBivisudim_2d_za\fP = 3"
.br
.ti -1c
.RI "integer, parameter \fBivisudim_1d_xza\fP = 4"
.br
.ti -1c
.RI "integer, parameter \fBx_pencil\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBy_pencil\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBz_pencil\fP = 3"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public io_tools_mod::generate_file_name (character(120), intent(out) flname, integer, intent(in) dmtag, character(*), intent(in) keyword, character(*), intent(in) extension, integer, intent(in), optional timetag)"

.SS "subroutine, public io_tools_mod::generate_pathfile_name (character(120), intent(out) flname, integer, intent(in) dmtag, character(*), intent(in) keyword, character(*), intent(in) path, character(*), intent(in) extension, integer, intent(in), optional timetag)"

.SS "subroutine, public io_tools_mod::initialize_decomp_io (type(\fBt_domain\fP), intent(in) dm)"

.SH "Variable Documentation"
.PP 
.SS "integer, parameter io_tools_mod::ivisudim_1d_xza = 4"

.SS "integer, parameter io_tools_mod::ivisudim_2d_xa = 1"

.SS "integer, parameter io_tools_mod::ivisudim_2d_ya = 2"

.SS "integer, parameter io_tools_mod::ivisudim_2d_za = 3"

.SS "integer, parameter io_tools_mod::ivisudim_3d = 0"

.SS "integer, parameter io_tools_mod::x_pencil = 1"

.SS "integer, parameter io_tools_mod::y_pencil = 2"

.SS "integer, parameter io_tools_mod::z_pencil = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
