.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/io_visulisation.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/io_visulisation.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBio_visulisation_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_ini\fP (dm)"
.br
.ti -1c
.RI "subroutine, private \fBio_visulisation_mod::write_snapshot_headerfooter\fP (dm, visuname, iheadfoot, iter)"
.br
.ti -1c
.RI "subroutine, private \fBio_visulisation_mod::write_field\fP (dm, var, dtmp, varname, visuname, attributetype, centring, iter)"
.br
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_flow_stat\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_thermo_stat\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBio_visulisation_mod::write_snapshot_any3darray\fP (var, varname, visuname, dtmp, dm, iter)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len= *), parameter \fBio_visulisation_mod::io_name\fP = 'solution\-io'"
.br
.ti -1c
.RI "integer, parameter \fBio_visulisation_mod::xdmf_header\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBio_visulisation_mod::xdmf_footer\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBio_visulisation_mod::plane_average\fP = \-1"
.br
.ti -1c
.RI "character(6), parameter \fBio_visulisation_mod::scalar\fP = 'Scalar'"
.br
.ti -1c
.RI "character(6), parameter \fBio_visulisation_mod::vector\fP = 'Vector'"
.br
.ti -1c
.RI "character(6), parameter \fBio_visulisation_mod::tensor\fP = 'Tensor'"
.br
.ti -1c
.RI "character(4), parameter \fBio_visulisation_mod::cell\fP = 'Cell'"
.br
.ti -1c
.RI "character(4), parameter \fBio_visulisation_mod::node\fP = 'Node'"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBio_visulisation_mod::nnd_visu\fP"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBio_visulisation_mod::ncl_visu\fP"
.br
.ti -1c
.RI "real(wp), dimension(:), allocatable \fBio_visulisation_mod::xp\fP"
.br
.ti -1c
.RI "real(wp), dimension(:), allocatable \fBio_visulisation_mod::yp\fP"
.br
.ti -1c
.RI "real(wp), dimension(:), allocatable \fBio_visulisation_mod::zp\fP"
.br
.ti -1c
.RI "character(6) \fBio_visulisation_mod::svisudim\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
