.TH "io_visulisation_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_visulisation_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_ini\fP (dm)"
.br
.ti -1c
.RI "subroutine, private \fBwrite_snapshot_headerfooter\fP (dm, visuname, iheadfoot, iter)"
.br
.ti -1c
.RI "subroutine, private \fBwrite_field\fP (dm, var, dtmp, varname, visuname, attributetype, centring, iter)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_flow_stat\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_thermo_stat\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_snapshot_any3darray\fP (var, varname, visuname, dtmp, dm, iter)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len= *), parameter \fBio_name\fP = 'solution\-io'"
.br
.ti -1c
.RI "integer, parameter \fBxdmf_header\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBxdmf_footer\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBplane_average\fP = \-1"
.br
.ti -1c
.RI "character(6), parameter \fBscalar\fP = 'Scalar'"
.br
.ti -1c
.RI "character(6), parameter \fBvector\fP = 'Vector'"
.br
.ti -1c
.RI "character(6), parameter \fBtensor\fP = 'Tensor'"
.br
.ti -1c
.RI "character(4), parameter \fBcell\fP = 'Cell'"
.br
.ti -1c
.RI "character(4), parameter \fBnode\fP = 'Node'"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBnnd_visu\fP"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBncl_visu\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:), allocatable \fBxp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:), allocatable \fByp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:), allocatable \fBzp\fP"
.br
.ti -1c
.RI "character(6) \fBsvisudim\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, private io_visulisation_mod::write_field (type(\fBt_domain\fP), intent(in) dm, real(\fBwp\fP), dimension(:, :, :), intent(in) var, type(decomp_info), intent(in) dtmp, character(len=*), intent(in) varname, character(len=*), intent(in) visuname, character(*), intent(in) attributetype, character(*), intent(in) centring, integer, intent(in), optional iter)\fC [private]\fP"

.SS "subroutine, public io_visulisation_mod::write_snapshot_any3darray (real(\fBwp\fP), dimension( dtmp%xsz(1), dtmp%xsz(2), dtmp%xsz(3) ), intent(in) var, character(*), intent(in) varname, character(*), intent(in) visuname, type(decomp_info), intent(in) dtmp, type(\fBt_domain\fP), intent(in) dm, integer, intent(in) iter)"

.SS "subroutine, public io_visulisation_mod::write_snapshot_flow (type(\fBt_flow\fP), intent(in) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_visulisation_mod::write_snapshot_flow_stat (type(\fBt_flow\fP), intent(in) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, private io_visulisation_mod::write_snapshot_headerfooter (type(\fBt_domain\fP), intent(in) dm, character(*), intent(in) visuname, integer, intent(in) iheadfoot, integer, intent(in) iter)\fC [private]\fP"

.SS "subroutine, public io_visulisation_mod::write_snapshot_ini (type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_visulisation_mod::write_snapshot_thermo (type(\fBt_thermo\fP), intent(in) tm, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public io_visulisation_mod::write_snapshot_thermo_stat (type(\fBt_thermo\fP), intent(in) tm, type(\fBt_domain\fP), intent(in) dm)"

.SH "Variable Documentation"
.PP 
.SS "character(4), parameter io_visulisation_mod::cell = 'Cell'"

.SS "character(len=*), parameter io_visulisation_mod::io_name = 'solution\-io'"

.SS "integer, dimension(:, :), allocatable io_visulisation_mod::ncl_visu"

.SS "integer, dimension(:, :), allocatable io_visulisation_mod::nnd_visu"

.SS "character(4), parameter io_visulisation_mod::node = 'Node'"

.SS "integer, parameter io_visulisation_mod::plane_average = \-1"

.SS "character(6), parameter io_visulisation_mod::scalar = 'Scalar'"

.SS "character(6) io_visulisation_mod::svisudim"

.SS "character(6), parameter io_visulisation_mod::tensor = 'Tensor'"

.SS "character(6), parameter io_visulisation_mod::vector = 'Vector'"

.SS "integer, parameter io_visulisation_mod::xdmf_footer = 2"

.SS "integer, parameter io_visulisation_mod::xdmf_header = 1"

.SS "real(\fBwp\fP), dimension(:), allocatable io_visulisation_mod::xp"

.SS "real(\fBwp\fP), dimension(:), allocatable io_visulisation_mod::yp"

.SS "real(\fBwp\fP), dimension(:), allocatable io_visulisation_mod::zp"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
