.TH "math_mod::tan_wp" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_mod::tan_wp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBtan_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBtan_dp\fP (r)"
.br
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "pure real(kind = \fBd15p\fP) function math_mod::tan_wp::tan_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::tan_wp::tan_sp (real(kind = \fBs6p\fP), intent(in) r)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
