.TH "math_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_mod
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBabs_prec\fP"
.br
.ti -1c
.RI "interface \fBabs_wp\fP"
.br
.ti -1c
.RI "interface \fBatan_wp\fP"
.br
.ti -1c
.RI "interface \fBcos_prec\fP"
.br
.ti -1c
.RI "interface \fBcos_wp\fP"
.br
.ti -1c
.RI "interface \fBsin_prec\fP"
.br
.ti -1c
.RI "interface \fBsin_wp\fP"
.br
.ti -1c
.RI "interface \fBsqrt_wp\fP"
.br
.ti -1c
.RI "interface \fBtan_wp\fP"
.br
.ti -1c
.RI "interface \fBtanh_wp\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "elemental real(kind=\fBs6p\fP) function \fBabs_sp\fP (r)"
.br
.ti -1c
.RI "elemental real(kind=\fBd15p\fP) function \fBabs_dp\fP (r)"
.br
.ti -1c
.RI "elemental real(kind=\fBs6p\fP) function \fBabs_csp\fP (r)"
.br
.ti -1c
.RI "elemental real(kind=\fBd15p\fP) function \fBabs_cdp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBsqrt_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBsqrt_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBsin_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBsin_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBcos_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBcos_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBtanh_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBtanh_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBtan_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBtan_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBs6p\fP) function \fBatan_sp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBd15p\fP) function \fBatan_dp\fP (r)"
.br
.ti -1c
.RI "pure real(kind=\fBwp\fP) function \fBheaviside_step\fP (r)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "elemental real(kind = \fBd15p\fP) function math_mod::abs_cdp (complex(kind = \fBd15p\fP), intent(in) r)"

.SS "elemental real(kind = \fBs6p\fP) function math_mod::abs_csp (complex(kind = \fBs6p\fP), intent(in) r)"

.SS "elemental real(kind = \fBd15p\fP) function math_mod::abs_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "elemental real(kind = \fBs6p\fP) function math_mod::abs_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::atan_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::atan_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::cos_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::cos_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBwp\fP) function math_mod::heaviside_step (real(kind = \fBwp\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::sin_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::sin_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::sqrt_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::sqrt_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::tan_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::tan_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SS "pure real(kind = \fBd15p\fP) function math_mod::tanh_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "pure real(kind = \fBs6p\fP) function math_mod::tanh_sp (real(kind = \fBs6p\fP), intent(in) r)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
