.TH "math_mod::abs_wp" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_mod::abs_wp
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "elemental real(kind=\fBs6p\fP) function \fBabs_sp\fP (r)"
.br
.ti -1c
.RI "elemental real(kind=\fBd15p\fP) function \fBabs_dp\fP (r)"
.br
.in -1c
.SH "Member Function/Subroutine Documentation"
.PP 
.SS "elemental real(kind = \fBd15p\fP) function math_mod::abs_wp::abs_dp (real(kind = \fBd15p\fP), intent(in) r)"

.SS "elemental real(kind = \fBs6p\fP) function math_mod::abs_wp::abs_sp (real(kind = \fBs6p\fP), intent(in) r)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
