.TH "mpi_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpi_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinitialize_mpi\fP ()"
.br
.RI "mpi initialisation\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBfinalise_mpi\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBierror\fP"
.br
.ti -1c
.RI "integer \fBnxdomain\fP"
.br
.ti -1c
.RI "integer \fBp_row\fP"
.br
.ti -1c
.RI "integer \fBp_col\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public mpi_mod::finalise_mpi"

.SS "subroutine, public mpi_mod::initialize_mpi"

.PP
mpi initialisation\&. 
.br
 this initialisation is a simple one\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain type 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "integer mpi_mod::ierror"

.SS "integer mpi_mod::nxdomain"

.SS "integer mpi_mod::p_col"

.SS "integer mpi_mod::p_row"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
