.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/mpi_mod.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/mpi_mod.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBmpi_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBmpi_mod::initialize_mpi\fP ()"
.br
.RI "mpi initialisation\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBmpi_mod::finalise_mpi\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBmpi_mod::ierror\fP"
.br
.ti -1c
.RI "integer \fBmpi_mod::nxdomain\fP"
.br
.ti -1c
.RI "integer \fBmpi_mod::p_row\fP"
.br
.ti -1c
.RI "integer \fBmpi_mod::p_col\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
