.TH "operations::t_xtdma_lhs" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operations::t_xtdma_lhs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad1x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd1x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd1x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd1x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad1x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd1x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd1x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd1x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad2x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd2x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd2x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd2x_p2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBad2x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbd2x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcd2x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdd2x_c2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBam1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbm1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcm1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdm1x_p2c\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBam1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBbm1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBcm1x_c2p\fP"
.br
.ti -1c
.RI "real(wp), dimension(:, :, :), allocatable \fBdm1x_c2p\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad1x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad1x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad2x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::ad2x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::am1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::am1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd1x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd1x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd2x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bd2x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bm1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::bm1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd1x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd1x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd2x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cd2x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cm1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::cm1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd1x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd1x_p2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd1x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd2x_c2c"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dd2x_p2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dm1x_c2p"

.SS "real(wp), dimension(:, :, :), allocatable operations::t_xtdma_lhs::dm1x_p2c"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
