.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_2ndderivcomp.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_2ndderivcomp.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBdecomp_2d_poisson::poisson_xxx\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdecomp_2d_poisson\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_finalize\fP"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_000\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_100\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_010\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_11x\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::abxyz\fP (ax, ay, az, bx, by, bz, nx, ny, nz, bcx, bcy, bcz)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::waves\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::matrice_refinement\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::avg3d\fP (var, avg)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
