.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_interface.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_interface.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBpoisson_interface_mod\fP"
.br
.ti -1c
.RI "module \fBdecomp_extended_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBpoisson_interface_mod::build_up_poisson_interface\fP (dm)"
.br
.ti -1c
.RI "real(mytype) function \fBrl\fP (complexnumber)"
.br
.ti -1c
.RI "real(mytype) function \fBiy\fP (complexnumber)"
.br
.ti -1c
.RI "complex(mytype) function \fBcx\fP (realpart, imaginarypart)"
.br
.ti -1c
.RI "subroutine \fBinversion5_v1\fP (aaa_in, eee, spi)"
.br
.ti -1c
.RI "subroutine \fBinversion5_v2\fP (aaa, eee, spi)"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_extended_mod::ypencil_index_lgl2ggl\fP (vin, vou, dtmp)"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_extended_mod::zpencil_index_llg2ggg\fP (vin, vou, dtmp)"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_extended_mod::zpencil_index_ggg2llg\fP (vin, vou, dtmp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBpoisson_interface_mod::istret\fP"
.br
.ti -1c
.RI "integer, parameter \fBpoisson_interface_mod::iforward\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBpoisson_interface_mod::ibackward\fP = \-1"
.br
.ti -1c
.RI "real(mytype) \fBpoisson_interface_mod::xlx\fP"
.br
.ti -1c
.RI "real(mytype) \fBpoisson_interface_mod::yly\fP"
.br
.ti -1c
.RI "real(mytype) \fBpoisson_interface_mod::zlz\fP"
.br
.ti -1c
.RI "logical \fBpoisson_interface_mod::nclx\fP"
.br
.ti -1c
.RI "logical \fBpoisson_interface_mod::ncly\fP"
.br
.ti -1c
.RI "logical \fBpoisson_interface_mod::nclz\fP"
.br
.ti -1c
.RI "integer \fBpoisson_interface_mod::nclx1\fP"
.br
.ti -1c
.RI "integer \fBpoisson_interface_mod::ncly1\fP"
.br
.ti -1c
.RI "integer \fBpoisson_interface_mod::nclz1\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::nx\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::ny\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::nz\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::nxm\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::nym\fP"
.br
.ti -1c
.RI "integer, save \fBpoisson_interface_mod::nzm\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::dx\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::dy\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::dz\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::alcaix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::acix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::bcix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::alcaiy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::aciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::bciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::alcaiz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::aciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::bciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::ailcaix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::aicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::bicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::cicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::dicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::ailcaiy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::aiciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::biciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::ciciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::diciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::ailcaiz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::aiciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::biciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::ciciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBpoisson_interface_mod::diciz6\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::zkz\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::zk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::ezs\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::yky\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::yk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::eys\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::xkx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::xk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBpoisson_interface_mod::exs\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "complex(mytype) function cx (real(mytype) realpart, real(mytype) imaginarypart)"

.SS "subroutine inversion5_v1 (complex(mytype), dimension(spi%yst(1):spi%yen(1),ny/2,spi%yst(3):spi%yen(3),5) aaa_in, complex(mytype), dimension(spi%yst(1):spi%yen(1),spi%yst(2):spi%yen(2),spi%yst(3):spi%yen(3)) eee, type(decomp_info) spi)"

.SS "subroutine inversion5_v2 (complex(mytype), dimension(spi%yst(1):spi%yen(1),nym,spi%yst(3):spi%yen(3),5) aaa, complex(mytype), dimension(spi%yst(1):spi%yen(1),nym,spi%yst(3):spi%yen(3)) eee, type(decomp_info) spi)"

.SS "real(mytype) function iy (complex(mytype) complexnumber)"

.SS "real(mytype) function rl (complex(mytype) complexnumber)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
