.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_1stderivcomp_reform.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_1stderivcomp_reform.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBdecomp_2d_poisson::poisson_xxx\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdecomp_2d_poisson\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_finalize\fP"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_000\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_100\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_010\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_11x\fP (rhs)"
.br
.ti -1c
.RI "subroutine, private \fBdecomp_2d_poisson::complex_half_unit\fP"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::fft3d_sp_shift_half_x0\fP (cw1, isign)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::fft3d_sp_shift_half_x1\fP (cw1, isign)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::fft3d_sp_shift_half_y0\fP (cw1, isign)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::fft3d_sp_shift_half_y1\fP (cw1)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::fft3d_sp_shift_half_z0\fP (cw1, isign)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::subroutine\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::matrice_refinement\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::avg3d\fP (var, avg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::cplx_circle_unit_halfx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::cplx_circle_unit_halfy\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::cplx_circle_unit_halfz\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::wx\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::wy\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::wz\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
