.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_1stderivcomp.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/poisson_1stderivcomp.f90
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "interface \fBdecomp_2d_poisson::poisson_xxx\fP"
.br
.in -1c
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdecomp_2d_poisson\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_init\fP ()"
.br
.ti -1c
.RI "subroutine, public \fBdecomp_2d_poisson::decomp_2d_poisson_finalize\fP"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_000\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_100\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_010\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::poisson_11x\fP (rhs)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::abxyz\fP (ax, ay, az, bx, by, bz, nx, ny, nz, bcx, bcy, bcz)"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::waves\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::matrice_refinement\fP ()"
.br
.ti -1c
.RI "subroutine \fBdecomp_2d_poisson::avg3d\fP (var, avg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "real(mytype), parameter \fBdecomp_2d_poisson::epsilon\fP = 1\&.e\-20_mytype"
.br
.ti -1c
.RI "integer, save \fBdecomp_2d_poisson::bcx\fP"
.br
.ti -1c
.RI "integer, save \fBdecomp_2d_poisson::bcy\fP"
.br
.ti -1c
.RI "integer, save \fBdecomp_2d_poisson::bcz\fP"
.br
.ti -1c
.RI "type(decomp_info), save \fBdecomp_2d_poisson::ph\fP"
.br
.ti -1c
.RI "type(decomp_info), save \fBdecomp_2d_poisson::sp\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::az\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::bz\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::ay\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::by\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::ax\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:), allocatable, save \fBdecomp_2d_poisson::bx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable, save \fBdecomp_2d_poisson::kxyz\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBdecomp_2d_poisson::a\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBdecomp_2d_poisson::a2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:,:), allocatable, save \fBdecomp_2d_poisson::a3\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::rw1\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::rw1b\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::rw2\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::rw2b\fP"
.br
.ti -1c
.RI "real(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::rw3\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw1\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw1b\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw22\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw2b\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:,:,:), allocatable \fBdecomp_2d_poisson::cw2c\fP"
.br
.ti -1c
.RI "logical, save \fBdecomp_2d_poisson::fft_initialised\fP = \&.false\&."
.br
.ti -1c
.RI "procedure(poisson_xxx), pointer, public \fBdecomp_2d_poisson::poisson\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
