.TH "poisson_interface_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
poisson_interface_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBbuild_up_poisson_interface\fP (dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer \fBistret\fP"
.br
.ti -1c
.RI "integer, parameter \fBiforward\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBibackward\fP = \-1"
.br
.ti -1c
.RI "real(mytype) \fBxlx\fP"
.br
.ti -1c
.RI "real(mytype) \fByly\fP"
.br
.ti -1c
.RI "real(mytype) \fBzlz\fP"
.br
.ti -1c
.RI "logical \fBnclx\fP"
.br
.ti -1c
.RI "logical \fBncly\fP"
.br
.ti -1c
.RI "logical \fBnclz\fP"
.br
.ti -1c
.RI "integer \fBnclx1\fP"
.br
.ti -1c
.RI "integer \fBncly1\fP"
.br
.ti -1c
.RI "integer \fBnclz1\fP"
.br
.ti -1c
.RI "integer, save \fBnx\fP"
.br
.ti -1c
.RI "integer, save \fBny\fP"
.br
.ti -1c
.RI "integer, save \fBnz\fP"
.br
.ti -1c
.RI "integer, save \fBnxm\fP"
.br
.ti -1c
.RI "integer, save \fBnym\fP"
.br
.ti -1c
.RI "integer, save \fBnzm\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdx\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdy\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdz\fP"
.br
.ti -1c
.RI "real(mytype), save \fBalcaix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBacix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbcix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBalcaiy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBaciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBalcaiz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBaciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBailcaix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBaicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBcicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdicix6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBailcaiy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBaiciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbiciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBciciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdiciy6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBailcaiz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBaiciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBbiciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBciciz6\fP"
.br
.ti -1c
.RI "real(mytype), save \fBdiciz6\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBzkz\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBzk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBezs\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fByky\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fByk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBeys\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBxkx\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBxk2\fP"
.br
.ti -1c
.RI "complex(mytype), dimension(:), allocatable, save \fBexs\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public poisson_interface_mod::build_up_poisson_interface (type(\fBt_domain\fP), intent(in) dm)"

.SH "Variable Documentation"
.PP 
.SS "real(mytype), save poisson_interface_mod::acix6"

.SS "real(mytype), save poisson_interface_mod::aciy6"

.SS "real(mytype), save poisson_interface_mod::aciz6"

.SS "real(mytype), save poisson_interface_mod::aicix6"

.SS "real(mytype), save poisson_interface_mod::aiciy6"

.SS "real(mytype), save poisson_interface_mod::aiciz6"

.SS "real(mytype), save poisson_interface_mod::ailcaix6"

.SS "real(mytype), save poisson_interface_mod::ailcaiy6"

.SS "real(mytype), save poisson_interface_mod::ailcaiz6"

.SS "real(mytype), save poisson_interface_mod::alcaix6"

.SS "real(mytype), save poisson_interface_mod::alcaiy6"

.SS "real(mytype), save poisson_interface_mod::alcaiz6"

.SS "real(mytype), save poisson_interface_mod::bcix6"

.SS "real(mytype), save poisson_interface_mod::bciy6"

.SS "real(mytype), save poisson_interface_mod::bciz6"

.SS "real(mytype), save poisson_interface_mod::bicix6"

.SS "real(mytype), save poisson_interface_mod::biciy6"

.SS "real(mytype), save poisson_interface_mod::biciz6"

.SS "real(mytype), save poisson_interface_mod::cicix6"

.SS "real(mytype), save poisson_interface_mod::ciciy6"

.SS "real(mytype), save poisson_interface_mod::ciciz6"

.SS "real(mytype), save poisson_interface_mod::dicix6"

.SS "real(mytype), save poisson_interface_mod::diciy6"

.SS "real(mytype), save poisson_interface_mod::diciz6"

.SS "real(mytype), save poisson_interface_mod::dx"

.SS "real(mytype), save poisson_interface_mod::dy"

.SS "real(mytype), save poisson_interface_mod::dz"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::exs"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::eys"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::ezs"

.SS "integer, parameter poisson_interface_mod::ibackward = \-1"

.SS "integer, parameter poisson_interface_mod::iforward = 1"

.SS "integer poisson_interface_mod::istret"

.SS "logical poisson_interface_mod::nclx"

.SS "integer poisson_interface_mod::nclx1"

.SS "logical poisson_interface_mod::ncly"

.SS "integer poisson_interface_mod::ncly1"

.SS "logical poisson_interface_mod::nclz"

.SS "integer poisson_interface_mod::nclz1"

.SS "integer, save poisson_interface_mod::nx"

.SS "integer, save poisson_interface_mod::nxm"

.SS "integer, save poisson_interface_mod::ny"

.SS "integer, save poisson_interface_mod::nym"

.SS "integer, save poisson_interface_mod::nz"

.SS "integer, save poisson_interface_mod::nzm"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::xk2"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::xkx"

.SS "real(mytype) poisson_interface_mod::xlx"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::yk2"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::yky"

.SS "real(mytype) poisson_interface_mod::yly"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::zk2"

.SS "complex(mytype), dimension(:), allocatable, save poisson_interface_mod::zkz"

.SS "real(mytype) poisson_interface_mod::zlz"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
