.TH "precision_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
precision_mod
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBi4\fP = selected_int_kind( 4 )"
.br
.ti -1c
.RI "integer, parameter \fBi8\fP = selected_int_kind( 8 )"
.br
.ti -1c
.RI "integer, parameter \fBi15\fP = selected_int_kind( 15 )"
.br
.ti -1c
.RI "integer, parameter \fBs6p\fP = selected_real_kind( p = 6, r = 37 )"
.br
.ti -1c
.RI "integer, parameter \fBd15p\fP = selected_real_kind( p = 15, r = 307 )"
.br
.ti -1c
.RI "integer, parameter \fBq33p\fP = selected_real_kind( p = 33, r = 4931 )"
.br
.ti -1c
.RI "integer, parameter \fBwp\fP = D15P"
.br
.ti -1c
.RI "integer, parameter \fBmpi_real_wp\fP = MPI_DOUBLE_PRECISION"
.br
.ti -1c
.RI "integer, parameter \fBmpi_cplx_wp\fP = MPI_DOUBLE_COMPLEX"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "integer, parameter precision_mod::d15p = selected_real_kind( p = 15, r = 307 )"

.SS "integer, parameter precision_mod::i15 = selected_int_kind( 15 )"

.SS "integer, parameter precision_mod::i4 = selected_int_kind( 4 )"

.SS "integer, parameter precision_mod::i8 = selected_int_kind( 8 )"

.SS "integer parameter precision_mod::mpi_cplx_wp = MPI_DOUBLE_COMPLEX"

.SS "integer parameter precision_mod::mpi_real_wp = MPI_DOUBLE_PRECISION"

.SS "integer, parameter precision_mod::q33p = selected_real_kind( p = 33, r = 4931 )"

.SS "integer, parameter precision_mod::s6p = selected_real_kind( p = 6, r = 37 )"

.SS "integer parameter precision_mod::wp = D15P"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
