.TH "random_number_generation_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
random_number_generation_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinitialize_random_number\fP (seed)"
.br
.ti -1c
.RI "subroutine, public \fBgenerate_rvec_random\fP (alo, ahi, n, a)"
.br
.ti -1c
.RI "subroutine, public \fBgenerate_r_random\fP (rlo, rhi, r)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public random_number_generation_mod::generate_r_random (real(\fBwp\fP) rlo, real(\fBwp\fP) rhi, real(\fBwp\fP) r)"

.SS "subroutine, public random_number_generation_mod::generate_rvec_random (real(\fBwp\fP) alo, real(\fBwp\fP) ahi, integer n, real(\fBwp\fP), dimension(n) a)"

.SS "subroutine, public random_number_generation_mod::initialize_random_number (integer seed)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
