.TH "solver_tools_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
solver_tools_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBupdate_re\fP (iter, fl)"
.br
.RI "The main code for initializing flow variables This subroutine is called once in \fBInitialize_chapsim\fP\&. "
.ti -1c
.RI "subroutine, public \fBupdate_prgr\fP (fl, tm)"
.br
.ti -1c
.RI "subroutine, public \fBcalculate_xz_mean_yprofile\fP (var, dtmp, n, varxz_work1)"
.br
.RI "The main code for initializing flow variables\&. "
.ti -1c
.RI "subroutine, public \fBadjust_to_xzmean_zero\fP (var, dtmp, n, varxz)"
.br
.RI ": MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBcheck_cfl_diffusion\fP (x2r, rre, dt)"
.br
.RI ": MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBcheck_cfl_convection\fP (u, v, w, dm)"
.br
.RI ": to check CFL for convection terms CFL = u^x/dx + v^y/dy + w^z/dz < limit MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBget_volumetric_average_3d\fP (is_ynp, ibcy, fbcy, dm, dtmp, var, fo_work)"
.br
.RI ": to calculate: fo = \\int_1^nx \\int_ This is based only y-direction stretching\&. "
.ti -1c
.RI "subroutine, public \fBfind_maximum_absvar3d\fP (var, str, fmt)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public solver_tools_mod::adjust_to_xzmean_zero (real(wp), dimension(dtmp%xsz(1), dtmp%xsz(2), dtmp%xsz(3)), intent(inout) var, type(decomp_info), intent(in) dtmp, integer, intent(in) n, real(wp), dimension(n), intent(in) varxz)"

.PP
: MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) 
.PP
\fBParameters\fP
.RS 4
\fI<br>\fP 
.RE
.PP

.SS "subroutine, public solver_tools_mod::calculate_xz_mean_yprofile (real(wp), dimension(dtmp%xsz(1), dtmp%xsz(2), dtmp%xsz(3)), intent(in) var, type(decomp_info), intent(in) dtmp, integer, intent(in) n, real(wp), dimension(n), intent(out), optional varxz_work1)"

.PP
The main code for initializing flow variables\&. not changing storage position, exclude b\&.c\&. values, for example, developing flow\&. MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, public solver_tools_mod::check_cfl_convection (real(wp), dimension(dm%dpcc%xsz(1), dm%dpcc%xsz(2), dm%dpcc%xsz(3)), intent(in) u, real(wp), dimension(dm%dcpc%xsz(1), dm%dcpc%xsz(2), dm%dcpc%xsz(3)), intent(in) v, real(wp), dimension(dm%dccp%xsz(1), dm%dccp%xsz(2), dm%dccp%xsz(3)), intent(in) w, type(\fBt_domain\fP), intent(in) dm)"

.PP
: to check CFL for convection terms CFL = u^x/dx + v^y/dy + w^z/dz < limit MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) 
.PP
\fBParameters\fP
.RS 4
\fI<br>\fP 
.RE
.PP

.SS "subroutine, public solver_tools_mod::check_cfl_diffusion (real(wp), dimension(3), intent(in) x2r, real(wp), intent(in) rre, real(wp), intent(in) dt)"

.PP
: MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) 
.PP
\fBParameters\fP
.RS 4
\fI<br>\fP 
.RE
.PP

.SS "subroutine, public solver_tools_mod::find_maximum_absvar3d (real(wp), dimension(:, :, :), intent(in) var, character(len = *), intent(in) str, character(len = *), intent(in) fmt)"

.SS "subroutine, public solver_tools_mod::get_volumetric_average_3d (logical, intent(in) is_ynp, integer, dimension(2), intent(in) ibcy, real(wp), dimension(2), intent(in) fbcy, type(\fBt_domain\fP), intent(in) dm, type(decomp_info), intent(in) dtmp, real(wp), dimension(:, :, :), intent(in) var, real(wp), intent(out) fo_work)"

.PP
: to calculate: fo = \\int_1^nx \\int_ This is based only y-direction stretching\&. 
.PP
\fBTodo\fP
.RS 4
Here is 2nd order Trapezoid Method\&. Need to improve! Check! 
.RE
.PP
Scope: mpi called-freq xdomain module all needed specified pubic MPI : default x-pencil working in : y-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) Y: index arrangment j'-1 j'-1 j' j'+1 j'+2 _|__\&.__|__\&.__|__\&.__|__\&.__|__\&.__ j-2 j-1 j j+1 j+2 
.PP
\fBParameters\fP
.RS 4
\fI<br>\fP 
.RE
.PP

.SS "subroutine, public solver_tools_mod::update_prgr (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm)"

.SS "subroutine, public solver_tools_mod::update_re (integer, intent(in) iter, type(\fBt_flow\fP), intent(inout) fl)"

.PP
The main code for initializing flow variables This subroutine is called once in \fBInitialize_chapsim\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fI<br>\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
