.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/statistics.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/statistics.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBstatistics_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBstatistics_mod::init_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBstatistics_mod::init_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBstatistics_mod::update_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBstatistics_mod::write_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBstatistics_mod::update_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBstatistics_mod::write_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, private \fBstatistics_mod::write_statistics_array\fP (var, keyword, idm, iter, dtmp)"
.br
.ti -1c
.RI "subroutine, private \fBstatistics_mod::read_statistics_array\fP (var, keyword, idm, iter, dtmp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(13), parameter \fBstatistics_mod::io_name\fP = 'statistics\-io'"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBstatistics_mod::ncl_stat\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
