.TH "statistics_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
statistics_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBinit_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBinit_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBupdate_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_statistics_flow\fP (fl, dm)"
.br
.ti -1c
.RI "subroutine, public \fBupdate_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBwrite_statistics_thermo\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, private \fBwrite_statistics_array\fP (var, keyword, idm, iter, dtmp)"
.br
.ti -1c
.RI "subroutine, private \fBread_statistics_array\fP (var, keyword, idm, iter, dtmp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "character(13), parameter \fBio_name\fP = 'statistics\-io'"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBncl_stat\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public statistics_mod::init_statistics_flow (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public statistics_mod::init_statistics_thermo (type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, private statistics_mod::read_statistics_array (real(wp), dimension(:, :, :), intent(in) var, character(*), intent(in) keyword, integer, intent(in) idm, integer, intent(in) iter, type(decomp_info), intent(in) dtmp)\fC [private]\fP"

.SS "subroutine, public statistics_mod::update_statistics_flow (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public statistics_mod::update_statistics_thermo (type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, private statistics_mod::write_statistics_array (real(wp), dimension( :, :, :), intent(in) var, character(*), intent(in) keyword, integer, intent(in) idm, integer, intent(in) iter, type(decomp_info), intent(in) dtmp)\fC [private]\fP"

.SS "subroutine, public statistics_mod::write_statistics_flow (type(\fBt_flow\fP), intent(in) fl, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, public statistics_mod::write_statistics_thermo (type(\fBt_thermo\fP), intent(in) tm, type(\fBt_domain\fP), intent(in) dm)"

.SH "Variable Documentation"
.PP 
.SS "character(13), parameter statistics_mod::io_name = 'statistics\-io'"

.SS "integer, dimension(:, :), allocatable statistics_mod::ncl_stat"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
