.TH "test_operations_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_operations_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBtest_interpolation\fP (dm)"
.br
.RI "To test this subroutine for mid-point interpolation\&. "
.ti -1c
.RI "subroutine, public \fBtest_1st_derivative\fP (dm)"
.br
.RI "To test this subroutine for mid-point interpolation\&. "
.ti -1c
.RI "subroutine, public \fBtest_2nd_derivative\fP (dm)"
.br
.RI "To test this subroutine for mid-point interpolation\&. "
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public test_operations_mod::test_1st_derivative (type(\fBt_domain\fP), intent(inout) dm)"

.PP
To test this subroutine for mid-point interpolation\&. This subroutine is called in \fBTest_algorithms\fP\&. Define the logicals to choose which test section is required\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain 
.RE
.PP

.SS "subroutine, public test_operations_mod::test_2nd_derivative (type(\fBt_domain\fP), intent(inout) dm)"

.PP
To test this subroutine for mid-point interpolation\&. This subroutine is called in \fBTest_algorithms\fP\&. Define the logicals to choose which test section is required\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain 
.RE
.PP

.SS "subroutine, public test_operations_mod::test_interpolation (type(\fBt_domain\fP), intent(inout) dm)"

.PP
To test this subroutine for mid-point interpolation\&. This subroutine is called in \fBTest_algorithms\fP\&. Define the logicals to choose which test section is required\&. 
.PP
\fBParameters\fP
.RS 4
\fId\fP domain 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
