.TH "thermo_info_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thermo_info_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, private \fBftp_is_t_in_scope\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to check the temperature limitations\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBftp_get_thermal_properties_dimensional_from_t\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known temperature\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBftp_refresh_thermal_properties_from_t_undim\fP (this)"
.br
.ti -1c
.RI "subroutine, private \fBftp_refresh_thermal_properties_from_h\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBftp_refresh_thermal_properties_from_dh\fP (this)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy per unit mass\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBftp_print\fP (this, unit, iotype, v_list, iostat, iomsg)"
.br
.RI "Defination of a procedure in the type t_fluidThermoProperty\&. to print out the thermal properties at the given element\&. 
.br
 "
.ti -1c
.RI "subroutine, private \fBftplist_sort_t_small2big\fP"
.br
.RI "Sort out the user given thermal property table based on the temperature from small to big\&. "
.ti -1c
.RI "subroutine, private \fBftplist_check_monotonicity_dh_of_hort\fP"
.br
.RI "Check the monotonicity of the $\\rho h$ along $h$ and $T$\&. "
.ti -1c
.RI "subroutine, private \fBbuildup_property_relations_from_table\fP"
.br
.RI "Building up the thermal property relations from the given table\&. This subroutine is called once after reading the table\&. [mpi] all ranks\&. "
.ti -1c
.RI "subroutine, private \fBftp_convert_undim_to_dim\fP (ftp_undim, ftp_dim)"
.br
.ti -1c
.RI "subroutine, private \fBbuildup_property_relations_from_function\fP"
.br
.RI "Building up the thermal property relations from defined relations\&. "
.ti -1c
.RI "subroutine, private \fBwrite_thermo_property\fP"
.br
.RI "Write out the rebuilt thermal property relations\&. "
.ti -1c
.RI "subroutine, private \fBinitialize_thermo_parameters\fP (tm)"
.br
.RI "Identify table or equations for thermal properties based on input fluid material\&. "
.ti -1c
.RI "subroutine, private \fBconvert_thermo_bc_from_dim_to_undim\fP (tm, dm)"
.br
.ti -1c
.RI "subroutine, public \fBinitialize_thermal_properties\fP (fl, tm)"
.br
.RI "Initialise thermal variables if ithermo = 1\&. 
.br
 "
.ti -1c
.RI "subroutine, public \fBbuildup_thermo_mapping_relations\fP (tm, dm)"
.br
.RI "The main code for thermal property initialisation\&. Scope: mpi called-freq xdomain all once all\&. "
.ti -1c
.RI "subroutine, public \fBupdate_thermal_properties\fP (fl, tm, dm)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, save \fBn_func2table\fP = 1024"
.br
.ti -1c
.RI "logical \fBis_ftplist_dim\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP), dimension(:), allocatable, save \fBftplist\fP"
.br
.ti -1c
.RI "type(\fBt_fluid_parameter\fP), save \fBfluidparam\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, private thermo_info_mod::buildup_property_relations_from_function\fC [private]\fP"

.PP
Building up the thermal property relations from defined relations\&. This subroutine is called once after defining the relations\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, private thermo_info_mod::buildup_property_relations_from_table\fC [private]\fP"

.PP
Building up the thermal property relations from the given table\&. This subroutine is called once after reading the table\&. [mpi] all ranks\&. 
.PP
\fBParameters\fP
.RS 4
\fIref_T0\fP reference temperature 
.RE
.PP

.SS "subroutine, public thermo_info_mod::buildup_thermo_mapping_relations (type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(inout) dm)"

.PP
The main code for thermal property initialisation\&. Scope: mpi called-freq xdomain all once all\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, private thermo_info_mod::convert_thermo_bc_from_dim_to_undim (type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(inout) dm)\fC [private]\fP"

.SS "subroutine, private thermo_info_mod::ftp_convert_undim_to_dim (type(\fBt_fluidthermoproperty\fP), intent(in) ftp_undim, type(\fBt_fluidthermoproperty\fP), intent(out) ftp_dim)\fC [private]\fP"

.SS "subroutine, private thermo_info_mod::ftp_get_thermal_properties_dimensional_from_t (type(\fBt_fluidthermoproperty\fP), intent(inout) this)\fC [private]\fP"

.PP
Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known temperature\&. 
.br
 This subroutine is called as required to update all thermal properties from the known temperature (dimensional or dimensionless)\&. 
.PP
\fBParameters\fP
.RS 4
\fIthis\fP a cell element with udf property 
.br
\fIdim\fP an optional indicator of dimensional /dimensionless T\&. Exsiting of \fBdim\fP indicates the known/given T is dimensional\&. Otherwise, not\&. 
.RE
.PP

.SS "subroutine, private thermo_info_mod::ftp_is_t_in_scope (type( \fBt_fluidthermoproperty\fP ), intent(in) this)\fC [private]\fP"

.PP
Defination of a procedure in the type t_fluidThermoProperty\&. to check the temperature limitations\&. 
.br
 This subroutine is called as required to check the temperature of given element is within the given limits as a single phase flow\&. 
.PP
\fBParameters\fP
.RS 4
\fIthis\fP a cell element with udf property 
.RE
.PP

.SS "subroutine, private thermo_info_mod::ftp_print (type(\fBt_fluidthermoproperty\fP), intent(in) this, integer, intent(in) unit, character(len = *), intent(in) iotype, integer, dimension(:), intent(in) v_list, integer, intent(out) iostat, character(len = *), intent(inout) iomsg)\fC [private]\fP"

.PP
Defination of a procedure in the type t_fluidThermoProperty\&. to print out the thermal properties at the given element\&. 
.br
 This subroutine is called as required to print out thermal properties for degbugging\&. 
.PP
\fBParameters\fP
.RS 4
\fIthis\fP a cell element with udf property 
.br
\fIunit\fP 
.br
 
.br
\fIiotype\fP 
.br
 
.br
\fIv_list\fP 
.br
 
.br
\fIiostat\fP 
.br
 
.br
\fIiomsg\fP 
.br
 
.RE
.PP

.SS "subroutine, public thermo_info_mod::ftp_refresh_thermal_properties_from_dh (type(\fBt_fluidthermoproperty\fP), intent(inout) this)"

.PP
Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy per unit mass\&. 
.br
 This subroutine is called as required to update all thermal properties from the known enthalpy per unit mass (dimensionless only)\&. 
.PP
\fBParameters\fP
.RS 4
\fIthis\fP a cell element with udf property 
.RE
.PP

.SS "subroutine, private thermo_info_mod::ftp_refresh_thermal_properties_from_h (type(\fBt_fluidthermoproperty\fP), intent(inout) this)\fC [private]\fP"

.PP
Defination of a procedure in the type t_fluidThermoProperty\&. to update the thermal properties based on the known enthalpy\&. 
.br
 This subroutine is called as required to update all thermal properties from the known enthalpy (dimensionless only)\&. 
.PP
\fBParameters\fP
.RS 4
\fIthis\fP a cell element with udf property 
.RE
.PP

.SS "subroutine, private thermo_info_mod::ftp_refresh_thermal_properties_from_t_undim (type(\fBt_fluidthermoproperty\fP), intent(inout) this)\fC [private]\fP"

.SS "subroutine, private thermo_info_mod::ftplist_check_monotonicity_dh_of_hort\fC [private]\fP"

.PP
Check the monotonicity of the $\\rho h$ along $h$ and $T$\&. This subroutine is called locally once building up the thermal property relationships\&. Non-monotonicity could happen in fluids at supercritical pressure when inproper reference temperature is given\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, private thermo_info_mod::ftplist_sort_t_small2big\fC [private]\fP"

.PP
Sort out the user given thermal property table based on the temperature from small to big\&. This subroutine is called locally once reading in the given thermal table\&. 
.PP
\fBParameters\fP
.RS 4
\fIlist\fP the thermal table element array 
.RE
.PP

.SS "subroutine, public thermo_info_mod::initialize_thermal_properties (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm)"

.PP
Initialise thermal variables if ithermo = 1\&. 
.br
 Scope: mpi called-freq xdomain module all once specified private 
.PP
\fBParameters\fP
.RS 4
\fIfl\fP flow type 
.br
\fItm\fP thermo type 
.RE
.PP

.SS "subroutine, private thermo_info_mod::initialize_thermo_parameters (type(\fBt_thermo\fP), intent(in) tm)\fC [private]\fP"

.PP
Identify table or equations for thermal properties based on input fluid material\&. This subroutine is called once in setting up thermal relations\&. [mpi] all ranks 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SS "subroutine, public thermo_info_mod::update_thermal_properties (type(\fBt_flow\fP), intent(inout) fl, type(\fBt_thermo\fP), intent(inout) tm, type(\fBt_domain\fP), intent(in) dm)"

.SS "subroutine, private thermo_info_mod::write_thermo_property\fC [private]\fP"

.PP
Write out the rebuilt thermal property relations\&. This subroutine is called for testing\&. 
.PP
\fBParameters\fP
.RS 4
\fInone\fP NA 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "type(\fBt_fluid_parameter\fP), save thermo_info_mod::fluidparam"

.SS "type(\fBt_fluidthermoproperty\fP), dimension(:), allocatable, save thermo_info_mod::ftplist"

.SS "logical thermo_info_mod::is_ftplist_dim"

.SS "integer, save thermo_info_mod::n_func2table = 1024"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
