.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/tools_solver.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/tools_solver.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBsolver_tools_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::update_re\fP (iter, fl)"
.br
.RI "The main code for initializing flow variables This subroutine is called once in \fBInitialize_chapsim\fP\&. "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::update_prgr\fP (fl, tm)"
.br
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::calculate_xz_mean_yprofile\fP (var, dtmp, n, varxz_work1)"
.br
.RI "The main code for initializing flow variables\&. "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::adjust_to_xzmean_zero\fP (var, dtmp, n, varxz)"
.br
.RI ": MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::check_cfl_diffusion\fP (x2r, rre, dt)"
.br
.RI ": MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::check_cfl_convection\fP (u, v, w, dm)"
.br
.RI ": to check CFL for convection terms CFL = u^x/dx + v^y/dy + w^z/dz < limit MPI : x-pencil (y) ^_____ _____ ______ |_____|_____|______| |_____|_____|______|__> (z) "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::get_volumetric_average_3d\fP (is_ynp, ibcy, fbcy, dm, dtmp, var, fo_work)"
.br
.RI ": to calculate: fo = \\int_1^nx \\int_ This is based only y-direction stretching\&. "
.ti -1c
.RI "subroutine, public \fBsolver_tools_mod::find_maximum_absvar3d\fP (var, str, fmt)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
