.TH "/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/tools_general.f90" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/wei.wang/Work/11_CHAPSim/CHAPSim/CHAPSim2/src/tools_general.f90
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "module \fBdecomp_operation_mod\fP"
.br
.ti -1c
.RI "module \fBcode_performance_mod\fP"
.br
.ti -1c
.RI "module \fBrandom_number_generation_mod\fP"
.br
.in -1c
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine \fBprint_error_msg\fP (msg)"
.br
.ti -1c
.RI "subroutine \fBprint_warning_msg\fP (msg)"
.br
.ti -1c
.RI "subroutine \fBprint_debug_start_msg\fP (msg)"
.br
.ti -1c
.RI "subroutine \fBprint_debug_mid_msg\fP (msg)"
.br
.ti -1c
.RI "subroutine \fBprint_debug_end_msg\fP"
.br
.ti -1c
.RI "subroutine \fBprint_3d_array\fP (var, nx, ny, nz, str)"
.br
.ti -1c
.RI "logical function \fBdecomp_operation_mod::is_decomp_same\fP (a, b)"
.br
.ti -1c
.RI "subroutine, private \fBcode_performance_mod::convert_sec_to_hms\fP (s, hrs, mins, secs)"
.br
.ti -1c
.RI "subroutine, public \fBcode_performance_mod::call_cpu_time\fP (itype, iterfrom, niter, iter)"
.br
.ti -1c
.RI "subroutine, public \fBrandom_number_generation_mod::initialize_random_number\fP (seed)"
.br
.ti -1c
.RI "subroutine, public \fBrandom_number_generation_mod::generate_rvec_random\fP (alo, ahi, n, a)"
.br
.ti -1c
.RI "subroutine, public \fBrandom_number_generation_mod::generate_r_random\fP (rlo, rhi, r)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_code_start\fP = 1"
.br
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_step_start\fP = 2"
.br
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_iter_start\fP = 3"
.br
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_iter_end\fP = 4"
.br
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_step_end\fP = 5"
.br
.ti -1c
.RI "integer, parameter \fBcode_performance_mod::cpu_time_code_end\fP = 6"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_code_start\fP"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_step_start\fP"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_iter_start\fP"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_iter_end\fP"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_step_end\fP"
.br
.ti -1c
.RI "real(wp), save \fBcode_performance_mod::t_code_end\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine print_3d_array (real(wp), dimension(nx, ny, nz), intent(in) var, integer, intent(in) nx, integer, intent(in) ny, integer, intent(in) nz, character(len=*), intent(in) str)"

.SS "subroutine print_debug_end_msg"

.SS "subroutine print_debug_mid_msg (character(len=*), intent(in) msg)"

.SS "subroutine print_debug_start_msg (character(len=*), intent(in) msg)"

.SS "subroutine print_error_msg (character(len=*), intent(in) msg)"

.SS "subroutine print_warning_msg (character(len=*), intent(in) msg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
