.TH "tridiagonal_matrix_algorithm" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tridiagonal_matrix_algorithm
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "subroutine, public \fBpreprocess_tdma_coeffs\fP (a, b, c, d, n)"
.br
.ti -1c
.RI "subroutine, private \fBsolve_tdma_basic\fP (x, a, b, c, d, n)"
.br
.ti -1c
.RI "subroutine, private \fBsolve_tdma_cyclic\fP (x, a, b, c, d, n)"
.br
.ti -1c
.RI "subroutine, public \fBsolve_tdma\fP (peri, x, a, b, c, d, n)"
.br
.ti -1c
.RI "subroutine, public \fBtest_tdma_noncyclic\fP"
.br
.ti -1c
.RI "subroutine, public \fBtest_tdma_cyclic\fP"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "subroutine, public tridiagonal_matrix_algorithm::preprocess_tdma_coeffs (real(wp), dimension(n), intent(in) a, real(wp), dimension(n), intent(in) b, real(wp), dimension(n), intent(inout) c, real(wp), dimension(n), intent(out) d, integer, intent(in) n)"

.SS "subroutine, public tridiagonal_matrix_algorithm::solve_tdma (logical, intent(in) peri, real(wp), dimension(n), intent(inout) x, real(wp), dimension(n), intent(in) a, real(wp), dimension(n), intent(in) b, real(wp), dimension(n), intent(in) c, real(wp), dimension(n), intent(in) d, integer, intent(in) n)"

.SS "subroutine, private tridiagonal_matrix_algorithm::solve_tdma_basic (real(wp), dimension(n), intent(inout) x, real(wp), dimension(n), intent(in) a, real(wp), dimension(n), intent(in) b, real(wp), dimension(n), intent(in) c, real(wp), dimension(n), intent(in) d, integer, intent(in) n)\fC [private]\fP"

.SS "subroutine, private tridiagonal_matrix_algorithm::solve_tdma_cyclic (real(wp), dimension(n), intent(inout) x, real(wp), dimension(n), intent(in) a, real(wp), dimension(n), intent(in) b, real(wp), dimension(n), intent(in) c, real(wp), dimension(n), intent(in) d, integer, intent(in) n)\fC [private]\fP"

.SS "subroutine, public tridiagonal_matrix_algorithm::test_tdma_cyclic"

.SS "subroutine, public tridiagonal_matrix_algorithm::test_tdma_noncyclic"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
