.TH "typeconvert_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typeconvert_mod
.SH SYNOPSIS
.br
.PP
.SS "Functions/Subroutines"

.in +1c
.ti -1c
.RI "character(len=20) function \fBint2str\fP (k)"
.br
.ti -1c
.RI "character(len=20) function \fBreal2str\fP (r)"
.br
.in -1c
.SH "Function/Subroutine Documentation"
.PP 
.SS "character(len=20) function typeconvert_mod::int2str (integer, intent(in) k)"

.SS "character(len=20) function typeconvert_mod::real2str (real(wp), intent(in) r)"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
