.TH "udf_type_mod::t_flow" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udf_type_mod::t_flow
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBidriven\fP"
.br
.ti -1c
.RI "integer \fBigravity\fP"
.br
.ti -1c
.RI "integer \fBinittype\fP"
.br
.ti -1c
.RI "integer \fBiterfrom\fP"
.br
.ti -1c
.RI "integer \fBinitreto\fP"
.br
.ti -1c
.RI "integer \fBniterflowstart\fP"
.br
.ti -1c
.RI "integer \fBniterflowend\fP"
.br
.ti -1c
.RI "integer \fBiteration\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBtime\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBren\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBrre\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(3) \fBinit_velo3d\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBreninit\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBdrvfc\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(3) \fBfgravity\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBnoiselevel\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBqx\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBqy\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBqz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBgx\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBgy\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBgz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBpres\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBpcor\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBpcor_zpencil_ggg\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBddens\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmvisc\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBddensm1\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBddensm2\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmx_rhs\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmy_rhs\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmz_rhs\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmx_rhs0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmy_rhs0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBmz_rhs0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :, :), allocatable \fBu_vector_mean\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBpr_mean\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :, :), allocatable \fBuu_tensor6_mean\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::ddens"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::ddensm1"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::ddensm2"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::drvfc"

.SS "real(\fBwp\fP), dimension(3) udf_type_mod::t_flow::fgravity"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::gx"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::gy"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::gz"

.SS "integer udf_type_mod::t_flow::idriven"

.SS "integer udf_type_mod::t_flow::igravity"

.SS "real(\fBwp\fP), dimension(3) udf_type_mod::t_flow::init_velo3d"

.SS "integer udf_type_mod::t_flow::initreto"

.SS "integer udf_type_mod::t_flow::inittype"

.SS "integer udf_type_mod::t_flow::iteration"

.SS "integer udf_type_mod::t_flow::iterfrom"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::mvisc"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::mx_rhs"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::mx_rhs0"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::my_rhs"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::my_rhs0"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::mz_rhs"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::mz_rhs0"

.SS "integer udf_type_mod::t_flow::niterflowend"

.SS "integer udf_type_mod::t_flow::niterflowstart"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::noiselevel"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::pcor"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::pcor_zpencil_ggg"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::pr_mean"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::pres"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::qx"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::qy"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_flow::qz"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::ren"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::reninit"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::rre"

.SS "real(\fBwp\fP) udf_type_mod::t_flow::time"

.SS "real(\fBwp\fP), dimension(:, :, :, :), allocatable udf_type_mod::t_flow::u_vector_mean"

.SS "real(\fBwp\fP), dimension(:, :, :, :), allocatable udf_type_mod::t_flow::uu_tensor6_mean"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
