.TH "udf_type_mod::t_fluid_parameter" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udf_type_mod::t_fluid_parameter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "character(len=64) \fBinputproperty\fP"
.br
.ti -1c
.RI "integer \fBifluid\fP"
.br
.ti -1c
.RI "integer \fBipropertystate\fP"
.br
.ti -1c
.RI "integer \fBnlist\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBtm0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBtb0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBhm0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(0:1) \fBcod\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(0:2) \fBcok\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBcob\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(\-2:2) \fBcocp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(\-1:3) \fBcoh\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(\-1:1) \fBcom\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBdhmax\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBdhmin\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP) \fBftp0ref\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP) \fBftpini\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::cob"

.SS "real(\fBwp\fP), dimension(\-2:2) udf_type_mod::t_fluid_parameter::cocp"

.SS "real(\fBwp\fP), dimension(0:1) udf_type_mod::t_fluid_parameter::cod"

.SS "real(\fBwp\fP), dimension(\-1:3) udf_type_mod::t_fluid_parameter::coh"

.SS "real(\fBwp\fP), dimension(0:2) udf_type_mod::t_fluid_parameter::cok"

.SS "real(\fBwp\fP), dimension(\-1:1) udf_type_mod::t_fluid_parameter::com"

.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::dhmax"

.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::dhmin"

.SS "type(\fBt_fluidthermoproperty\fP) udf_type_mod::t_fluid_parameter::ftp0ref"

.SS "type(\fBt_fluidthermoproperty\fP) udf_type_mod::t_fluid_parameter::ftpini"

.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::hm0"

.SS "integer udf_type_mod::t_fluid_parameter::ifluid"

.SS "character(len = 64) udf_type_mod::t_fluid_parameter::inputproperty"

.SS "integer udf_type_mod::t_fluid_parameter::ipropertystate"

.SS "integer udf_type_mod::t_fluid_parameter::nlist"

.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::tb0"

.SS "real(\fBwp\fP) udf_type_mod::t_fluid_parameter::tm0"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
