.TH "udf_type_mod::t_domain" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udf_type_mod::t_domain
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "logical, dimension(3) \fBis_periodic\fP"
.br
.ti -1c
.RI "logical, dimension(3) \fBis_stretching\fP"
.br
.ti -1c
.RI "logical \fBis_compact_scheme\fP"
.br
.ti -1c
.RI "logical \fBis_thermo\fP"
.br
.ti -1c
.RI "integer \fBidom\fP"
.br
.ti -1c
.RI "integer \fBicase\fP"
.br
.ti -1c
.RI "integer \fBicoordinate\fP"
.br
.ti -1c
.RI "integer \fBicht\fP"
.br
.ti -1c
.RI "integer \fBitimescheme\fP"
.br
.ti -1c
.RI "integer \fBiviscous\fP"
.br
.ti -1c
.RI "integer \fBiaccuracy\fP"
.br
.ti -1c
.RI "integer \fBckpt_nfre\fP"
.br
.ti -1c
.RI "integer \fBvisu_nfre\fP"
.br
.ti -1c
.RI "integer \fBvisu_idim\fP"
.br
.ti -1c
.RI "integer, dimension(3) \fBvisu_nskip\fP"
.br
.ti -1c
.RI "integer \fBstat_istart\fP"
.br
.ti -1c
.RI "integer, dimension(3) \fBstat_nskip\fP"
.br
.ti -1c
.RI "integer \fBnsubitr\fP"
.br
.ti -1c
.RI "integer \fBistret\fP"
.br
.ti -1c
.RI "integer, dimension(3) \fBnc\fP"
.br
.ti -1c
.RI "integer, dimension(3) \fBnp_geo\fP"
.br
.ti -1c
.RI "integer, dimension(3) \fBnp\fP"
.br
.ti -1c
.RI "integer \fBproben\fP"
.br
.ti -1c
.RI "integer, dimension(2, 5) \fBibcx\fP"
.br
.ti -1c
.RI "integer, dimension(2, 5) \fBibcy\fP"
.br
.ti -1c
.RI "integer, dimension(2, 5) \fBibcz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(2, 5) \fBfbcx\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(2, 5) \fBfbcy\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(2, 5) \fBfbcz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(2, 3) \fBfbc_vism\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(2, 3) \fBfbc_dend\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBlxx\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBlyt\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBlyb\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBlzz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBrstret\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBdt\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(3) \fBh\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(3) \fBh1r\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(3) \fBh2r\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(0:3) \fBtgamma\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(0:3) \fBtzeta\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(0:3) \fBtalpha\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBsigma1p\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBsigma2p\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdccc\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdpcc\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdcpc\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdccp\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdppc\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdpcp\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdcpp\fP"
.br
.ti -1c
.RI "type(decomp_info) \fBdppp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :), allocatable \fBymappingpt\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :), allocatable \fBymappingcc\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:), allocatable \fByp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:), allocatable \fByc\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :), allocatable \fBprobexyz\fP"
.br
.ti -1c
.RI "logical, dimension(:), allocatable \fBprobe_is_in\fP"
.br
.ti -1c
.RI "integer, dimension(:, :), allocatable \fBprobexid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "integer udf_type_mod::t_domain::ckpt_nfre"

.SS "type(decomp_info) udf_type_mod::t_domain::dccc"

.SS "type(decomp_info) udf_type_mod::t_domain::dccp"

.SS "type(decomp_info) udf_type_mod::t_domain::dcpc"

.SS "type(decomp_info) udf_type_mod::t_domain::dcpp"

.SS "type(decomp_info) udf_type_mod::t_domain::dpcc"

.SS "type(decomp_info) udf_type_mod::t_domain::dpcp"

.SS "type(decomp_info) udf_type_mod::t_domain::dppc"

.SS "type(decomp_info) udf_type_mod::t_domain::dppp"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::dt"

.SS "real(\fBwp\fP), dimension(2, 3) udf_type_mod::t_domain::fbc_dend"

.SS "real(\fBwp\fP), dimension(2, 3) udf_type_mod::t_domain::fbc_vism"

.SS "real(\fBwp\fP), dimension(2, 5) udf_type_mod::t_domain::fbcx"

.SS "real(\fBwp\fP), dimension(2, 5) udf_type_mod::t_domain::fbcy"

.SS "real(\fBwp\fP), dimension(2, 5) udf_type_mod::t_domain::fbcz"

.SS "real(\fBwp\fP), dimension(3) udf_type_mod::t_domain::h"

.SS "real(\fBwp\fP), dimension(3) udf_type_mod::t_domain::h1r"

.SS "real(\fBwp\fP), dimension(3) udf_type_mod::t_domain::h2r"

.SS "integer udf_type_mod::t_domain::iaccuracy"

.SS "integer, dimension(2, 5) udf_type_mod::t_domain::ibcx"

.SS "integer, dimension(2, 5) udf_type_mod::t_domain::ibcy"

.SS "integer, dimension(2, 5) udf_type_mod::t_domain::ibcz"

.SS "integer udf_type_mod::t_domain::icase"

.SS "integer udf_type_mod::t_domain::icht"

.SS "integer udf_type_mod::t_domain::icoordinate"

.SS "integer udf_type_mod::t_domain::idom"

.SS "logical udf_type_mod::t_domain::is_compact_scheme"

.SS "logical, dimension(3) udf_type_mod::t_domain::is_periodic"

.SS "logical, dimension(3) udf_type_mod::t_domain::is_stretching"

.SS "logical udf_type_mod::t_domain::is_thermo"

.SS "integer udf_type_mod::t_domain::istret"

.SS "integer udf_type_mod::t_domain::itimescheme"

.SS "integer udf_type_mod::t_domain::iviscous"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::lxx"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::lyb"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::lyt"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::lzz"

.SS "integer, dimension(3) udf_type_mod::t_domain::nc"

.SS "integer, dimension(3) udf_type_mod::t_domain::np"

.SS "integer, dimension(3) udf_type_mod::t_domain::np_geo"

.SS "integer udf_type_mod::t_domain::nsubitr"

.SS "logical, dimension(:), allocatable udf_type_mod::t_domain::probe_is_in"

.SS "integer udf_type_mod::t_domain::proben"

.SS "integer, dimension(:, :), allocatable udf_type_mod::t_domain::probexid"

.SS "real(\fBwp\fP), dimension(:, :), allocatable udf_type_mod::t_domain::probexyz"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::rstret"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::sigma1p"

.SS "real(\fBwp\fP) udf_type_mod::t_domain::sigma2p"

.SS "integer udf_type_mod::t_domain::stat_istart"

.SS "integer, dimension(3) udf_type_mod::t_domain::stat_nskip"

.SS "real(\fBwp\fP), dimension(0:3) udf_type_mod::t_domain::talpha"

.SS "real(\fBwp\fP), dimension(0:3) udf_type_mod::t_domain::tgamma"

.SS "real(\fBwp\fP), dimension (0:3) udf_type_mod::t_domain::tzeta"

.SS "integer udf_type_mod::t_domain::visu_idim"

.SS "integer udf_type_mod::t_domain::visu_nfre"

.SS "integer, dimension(3) udf_type_mod::t_domain::visu_nskip"

.SS "real(\fBwp\fP), dimension(:), allocatable udf_type_mod::t_domain::yc"

.SS "real(\fBwp\fP), dimension(:, :), allocatable udf_type_mod::t_domain::ymappingcc"

.SS "real(\fBwp\fP), dimension(:, :), allocatable udf_type_mod::t_domain::ymappingpt"

.SS "real(\fBwp\fP), dimension(:), allocatable udf_type_mod::t_domain::yp"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
