.TH "udf_type_mod::t_thermo" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udf_type_mod::t_thermo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBifluid\fP"
.br
.ti -1c
.RI "integer \fBinittype\fP"
.br
.ti -1c
.RI "integer \fBiterfrom\fP"
.br
.ti -1c
.RI "integer \fBiteration\fP"
.br
.ti -1c
.RI "integer \fBniterthermostart\fP"
.br
.ti -1c
.RI "integer \fBniterthermoend\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBref_l0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBref_t0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBinit_t0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBtime\fP"
.br
.ti -1c
.RI "real(\fBwp\fP) \fBrprren\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP), dimension(2) \fBftpbcx\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP), dimension(2) \fBftpbcy\fP"
.br
.ti -1c
.RI "type(\fBt_fluidthermoproperty\fP), dimension(2) \fBftpbcz\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBdh\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBhenth\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBkcond\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBttemp\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBene_rhs\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBene_rhs0\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBt_mean\fP"
.br
.ti -1c
.RI "real(\fBwp\fP), dimension(:, :, :), allocatable \fBtt_mean\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::dh"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::ene_rhs"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::ene_rhs0"

.SS "type(\fBt_fluidthermoproperty\fP), dimension(2) udf_type_mod::t_thermo::ftpbcx"

.SS "type(\fBt_fluidthermoproperty\fP), dimension(2) udf_type_mod::t_thermo::ftpbcy"

.SS "type(\fBt_fluidthermoproperty\fP), dimension(2) udf_type_mod::t_thermo::ftpbcz"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::henth"

.SS "integer udf_type_mod::t_thermo::ifluid"

.SS "real(\fBwp\fP) udf_type_mod::t_thermo::init_t0"

.SS "integer udf_type_mod::t_thermo::inittype"

.SS "integer udf_type_mod::t_thermo::iteration"

.SS "integer udf_type_mod::t_thermo::iterfrom"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::kcond"

.SS "integer udf_type_mod::t_thermo::niterthermoend"

.SS "integer udf_type_mod::t_thermo::niterthermostart"

.SS "real(\fBwp\fP) udf_type_mod::t_thermo::ref_l0"

.SS "real(\fBwp\fP) udf_type_mod::t_thermo::ref_t0"

.SS "real(\fBwp\fP) udf_type_mod::t_thermo::rprren"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::t_mean"

.SS "real(\fBwp\fP) udf_type_mod::t_thermo::time"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::tt_mean"

.SS "real(\fBwp\fP), dimension(:, :, :), allocatable udf_type_mod::t_thermo::ttemp"


.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
