.TH "udf_type_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udf_type_mod
.SH SYNOPSIS
.br
.PP
.SS "Data Types"

.in +1c
.ti -1c
.RI "type \fBt_domain\fP"
.br
.ti -1c
.RI "type \fBt_flow\fP"
.br
.ti -1c
.RI "type \fBt_fluid_parameter\fP"
.br
.ti -1c
.RI "type \fBt_fluidthermoproperty\fP"
.br
.ti -1c
.RI "type \fBt_thermo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
