.TH "vars_df_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vars_df_mod
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "type(\fBt_domain\fP), dimension(:), allocatable, save \fBdomain\fP"
.br
.ti -1c
.RI "type(\fBt_flow\fP), dimension(:), allocatable, save \fBflow\fP"
.br
.ti -1c
.RI "type(\fBt_thermo\fP), dimension(:), allocatable, save \fBthermo\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "type(\fBt_domain\fP), dimension(:), allocatable, save vars_df_mod::domain"

.SS "type(\fBt_flow\fP), dimension(:), allocatable, save vars_df_mod::flow"

.SS "type(\fBt_thermo\fP), dimension(:), allocatable, save vars_df_mod::thermo"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
