.TH "wtformat_mod" 3 "Thu Jan 26 2023" "CHAPSim2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wtformat_mod
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "character(len=17) \fBwrtfmt1i\fP = '(2X, A48, 1I20\&.1)'"
.br
.ti -1c
.RI "character(len=17) \fBwrtfmt2i\fP = '(2X, A48, 2I10\&.1)'"
.br
.ti -1c
.RI "character(len=17) \fBwrtfmt3i\fP = '(2X, A48, 3I10\&.1)'"
.br
.ti -1c
.RI "character(len=17) \fBwrtfmt4i\fP = '(2X, A48, 4I10\&.1)'"
.br
.ti -1c
.RI "character(len=17) \fBwrtfmt1r\fP = '(2X, A48, 1F20\&.6)'"
.br
.ti -1c
.RI "character(len=17) \fBwrtfmt2r\fP = '(2X, A48, 2F10\&.6)'"
.br
.ti -1c
.RI "character(len=18) \fBwrtfmt3r\fP = '(2X, A48, 3F23\&.15)'"
.br
.ti -1c
.RI "character(len=19) \fBwrtfmt1e\fP = '(2X, A48, 1ES23\&.15)'"
.br
.ti -1c
.RI "character(len=25) \fBwrtfmt1i1r\fP = '(2X, A48, 1I10\&.1, 1F10\&.6)'"
.br
.ti -1c
.RI "character(len=25) \fBwrtfmt2i2r\fP = '(2X, A48, 2I10\&.1, 2F10\&.6)'"
.br
.ti -1c
.RI "character(len=14) \fBwrtfmt1s\fP = '(2X, A48, A20)'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "character(len = 19) wtformat_mod::wrtfmt1e = '(2X, A48, 1ES23\&.15)'"

.SS "character(len = 17) wtformat_mod::wrtfmt1i = '(2X, A48, 1I20\&.1)'"

.SS "character(len = 25) wtformat_mod::wrtfmt1i1r = '(2X, A48, 1I10\&.1, 1F10\&.6)'"

.SS "character(len = 17) wtformat_mod::wrtfmt1r = '(2X, A48, 1F20\&.6)'"

.SS "character(len = 14) wtformat_mod::wrtfmt1s = '(2X, A48, A20)'"

.SS "character(len = 17) wtformat_mod::wrtfmt2i = '(2X, A48, 2I10\&.1)'"

.SS "character(len = 25) wtformat_mod::wrtfmt2i2r = '(2X, A48, 2I10\&.1, 2F10\&.6)'"

.SS "character(len = 17) wtformat_mod::wrtfmt2r = '(2X, A48, 2F10\&.6)'"

.SS "character(len = 17) wtformat_mod::wrtfmt3i = '(2X, A48, 3I10\&.1)'"

.SS "character(len = 18) wtformat_mod::wrtfmt3r = '(2X, A48, 3F23\&.15)'"

.SS "character(len = 17) wtformat_mod::wrtfmt4i = '(2X, A48, 4I10\&.1)'"

.SH "Author"
.PP 
Generated automatically by Doxygen for CHAPSim2 from the source code\&.
